// Cached Checkpoints
const checkpointCache = {};

// Checkpoints Maps
const checkpointNameMapping = {
    // Anime
    "Anime/animagineXLV31_v31.safetensors": {
        displayName: "Animagine XL V3.1 | v3.1",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: true,
        nsfw: true,
    },
    "Anime/autismmixSDXL_autismmixPony.safetensors": {
        displayName: "AutismMix SDXL | AutismMix_pony",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: true,
        nsfw: true,
    },
    "Anime/nngmixXL_v42.safetensors": {
        displayName: "NNGMIX-XL | v4.2",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: true,
        nsfw: true,
    },
    // DMD2
    "DMD2/asianRealismByStable_v10DMD2.safetensors": {
        displayName: "Asian_Realism_By_Stable_Yogi (ILLUS) | v1.0_DMD2",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: false,
        nsfw: true,
    },
    "DMD2/centerfold_versionXIDmd2.safetensors": {
        displayName: "Centerfold | version XI dmd2",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: false,
        nsfw: true,
    },
    "DMD2/cognitiveriver_illustriousV10.safetensors": {
        displayName: "CognitiveRiver | Illustrious v1.0",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: false,
        nsfw: true,
    },
    "DMD2/epicrealismXL_vxviLastfameDMD2.safetensors": {
        displayName: "epiCRealism XL | VXVI - LastFAME DMD2 (Realism)",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: false,
        nsfw: true,
    },
    "DMD2/gonzalomoDMD_v11.safetensors": {
        displayName: "GonzaLomo DMD | v1.1",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: false,
        nsfw: true,
    },
    "DMD2/lustifySDXLNSFW_endgameDMD2.safetensors": {
        displayName: "LUSTIFY! [SDXL NSFW checkpoint] | ENDGAME ⚡DMD2⚡",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: false,
        nsfw: true,
    },
    "DMD2/neuralSoup_v10.safetensors": {
        displayName: "Neural Soup | v1.0",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: false,
        nsfw: true,
    },
    "DMD2/neuralStew_v10.safetensors": {
        displayName: "Neural Stew | v1.0",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: false,
        nsfw: true,
    },
    "DMD2/realismSDXLByStable_v60XLDMD2.safetensors": {
        displayName: "Realism_SDXL_By_Stable_Yogi | v6.0_XL_DMD2",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: false,
        nsfw: true,
    },
    "DMD2/realustriousPonyXL_dmd.safetensors": {
        displayName: "Realustrious Pony XL | DMD",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: false,
        nsfw: true,
    },
    "DMD2/sirenForge_v21OldeskoolAnalog.safetensors": {
        displayName: "Siren Forge | v2.1 (OldeSkool Analog)",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: false,
        nsfw: true,
    },
    "DMD2/splashedMixDMD_v40.safetensors": {
        displayName: "Splashed Mix DMD | v4.0",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: false,
        nsfw: true,
    },
    "DMD2/ultraRealisticBy_v10DMD2.safetensors": {
        displayName: "Ultra Realistic By Stable Yogi | v1.0_DMD2",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: false,
        nsfw: true,
    },
    "DMD2/xxxRay_dmd2.safetensors": {
        displayName: "XXX-Ray | DMD2",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: false,
        nsfw: true,
    },

    // Illustrious
    "Illustrious/asianRealismByStable_v10FP16.safetensors": {
        displayName: "Asian_Realism_By_Stable_Yogi (ILLUS) | v1.0_FP16",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: true,
        nsfw: true,
    },
    "Illustrious/babesIllustriousBy_v30BF16.safetensors": {
        displayName: "Babes_Illustrious_By_Stable_Yogi | v3.0_BF16",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: true,
        nsfw: true,
    },
    "Illustrious/cyberillustrious_v35.safetensors": {
        displayName: "CyberIllustrious | CyberRealistic | v3.5",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: true,
        nsfw: true,
    },
    "Illustrious/illustriousRealismBy_v10VAE.safetensors": {
        displayName: "Illustrious Realism by klaabu | v1.0 + VAE",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: true,
        nsfw: true,
    },
    "Illustrious/jedpointreal_v1ILVae.safetensors": {
        displayName: "JedpointReal | V1 IL + Vae",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: true,
        nsfw: true,
    },
    "Illustrious/jibMixIllustrious_v20Revelation.safetensors": {
        displayName: "Jib Mix Illustrious Realistic | v2.0 Revelation",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: true,
        nsfw: true,
    },
    "Illustrious/perfection3DILXLIllustrious_v11.safetensors": {
        displayName: "Perfection 3D [ILXL / Illustrious XL] - NSFW / SFW Checkpoint | v1.1",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: true,
        nsfw: true,
    },
    "Illustrious/otherworldIDXLSDXL_v10.safetensors": {
        displayName: "Otherworld IDXL/SDXL Hybrid | v1.0",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: true,
        nsfw: true,
    },
    "Illustrious/perfectionRealisticILXL_v22.safetensors": {
        displayName: "Perfection Realistic [ILXL / Illustrious XL] - NSFW / SFW Checkpoint | v2.2",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: true,
        nsfw: true,
    },
    "Illustrious/pornmasterPro_realismILV1VAE.safetensors": {
        displayName: "PornMaster-Pro 色情大师- Illustrious & noob | Realism-IL-V1-VAE",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: true,
        nsfw: true,
    },
    "Illustrious/realCosplayerUNCEN_v10.safetensors": {
        displayName: "Real_Cosplayer_UNCEN [ILLUS/NOOB] | v1.0",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: true,
        nsfw: true,
    },
    "Illustrious/realismFusion_v10.safetensors": {
        displayName: "Realism Fusion | Illustrious | Realistic | v1.0",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: true,
        nsfw: true,
    },
    "Illustrious/reallybiglust_hibridIllustrious.safetensors": {
        displayName: "ReallyBigLust - Illustrious Realistic | Hibrid Illustrious-SDXL",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: true,
        nsfw: true,
    },
    "Illustrious/reallybiglust_v095LoraCompatible.safetensors": {
        displayName: "ReallyBigLust - Illustrious Realistic | v0.95 LoRA Compatible",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: true,
        nsfw: true,
    },
    "Illustrious/redcraftCADSUpdatedMar11_illust3relustion.safetensors": {
        displayName:
            "RedCraft | 红潮 CADS | UPdated-Mar18 | Commercial & Advertising Design System | Illust3Relustion🔥",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: true,
        nsfw: true,
    },
    "Illustrious/reijality_v10.safetensors": {
        displayName: "Reijality | v1.0",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: true,
        nsfw: true,
    },
    "Illustrious/shutter_v20.safetensors": {
        displayName: "Shutter | v2.0",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: true,
        nsfw: true,
    },

    // Pony
    "Pony/asianRealismByStable_v10FP16.safetensors": {
        displayName: "Asian_Realism_By_Stable_Yogi | v1.0_FP16",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: true,
        nsfw: true,
    },
    "Pony/cyberrealisticPony_v90Alt2.safetensors": {
        displayName: "CyberRealistic Pony | v9.0 Alt 2",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: true,
        nsfw: true,
    },
    "Pony/fasercore_v30PonyFP16.safetensors": {
        displayName: "FaserCore | v3.0_Pony_FP16",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: true,
        nsfw: true,
    },
    "Pony/fucktasticRealCheckpointPony_21.safetensors": {
        displayName: "Fucktastic Real Checkpoint [Pony/PDXL Porn] [Realistic] [NSFW/SFW] | v2.1",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: true,
        nsfw: true,
    },
    "Pony/iniverseMixSFWNSFW_ponyRealGuofengV50C.safetensors": {
        displayName: "iNiverse Mix(SFW & NSFW) | Pony Real GuoFeng v5.0C🔥",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: true,
        nsfw: true,
    },
    "Pony/likeRealityPonyBy_v20VAE.safetensors": {
        displayName: "Like Reality Pony by Ethanar | v2.0 VAE",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: true,
        nsfw: true,
    },
    "Pony/novaRealityXL_v70.safetensors": {
        displayName: "Nova Reality XL | v7.0",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: true,
        nsfw: true,
    },
    "Pony/realDream_sdxlPony15.safetensors": {
        displayName: "Real Dream | SDXL Pony 15",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: true,
        nsfw: true,
    },
    "Pony/ultraRealisticBy_v10FP16.safetensors": {
        displayName: "Ultra Realistic By Stable Yogi | v1.0_FP16",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: true,
        nsfw: true,
    },

    // SDXL
    "SDXL/1girlPrinter20_v10.safetensors": {
        displayName: "1girl printer 2.0 | v1.0",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: true,
        nsfw: true,
    },
    "SDXL/agxl_V2.safetensors": {
        displayName: "AGXL | AGXL_v2",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: true,
        nsfw: true,
    },
    "SDXL/AiprealisticSDXLNSFW_v10.safetensors": {
        displayName: "真实感写实大模型AIPRealistic_SDXL_NSFW | v1.0",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: true,
        nsfw: true,
    },
    "SDXL/annolustxl_v2.safetensors": {
        displayName: "ANNOLustXL | ANNOLustXLV2",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: true,
        nsfw: true,
    },
    "SDXL/beyondimaginationxl_v0005Fix.safetensors": {
        displayName: "BeyondImaginationXL | v0_005_Fix",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: true,
        nsfw: true,
    },
    "SDXL/biglust17_v17.safetensors": {
        displayName: "Big Lust | v1.7",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: true,
        nsfw: true,
    },
    "SDXL/biglustydonutmixNSFW_v12.safetensors": {
        displayName: "BigLustyDonutMix (NSFW Realism) | v1.2",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: true,
        nsfw: true,
    },
    "SDXL/boomerArtModelBAM_bamV2.safetensors": {
        displayName: "Boomer Art Model (BAM!) | BAM_v2",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: true,
        nsfw: true,
    },
    "SDXL/chirps_v1.safetensors": {
        displayName: "chirps | v1",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: true,
        nsfw: true,
    },
    "SDXL/clarityXL_v20.safetensors": {
        displayName: "Clarity XL | v2.0",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: true,
        nsfw: true,
    },
    "SDXL/cyberprimeXL_v11.safetensors": {
        displayName: "CyberPrime XL| v1.1",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: true,
        nsfw: true,
    },
    "SDXL/cyberrealisticXL_v53.safetensors": {
        displayName: "CyberRealistic XL | v5.3",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: true,
        nsfw: true,
    },
    "SDXL/donutsdeliverymixV4_v4.safetensors": {
        displayName: "DonutsDeliveryMix V4 - NSFW Photorealism | V4",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: true,
        nsfw: true,
    },
    "SDXL/d33psixSDXL_d33psixSDXL.safetensors": {
        displayName: "D33PSIX - SDXL | D33PSIX - SDXL",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: true,
        nsfw: true,
    },
    "SDXL/epicjoy_alpha.safetensors": {
        displayName: "EpicJOY | alpha",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: true,
        nsfw: true,
    },
    "SDXL/epicjuggernautxl_vxvXI.safetensors": {
        displayName: "EpicJuggernautXL | VXV+XI",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: true,
        nsfw: false,
    },
    "SDXL/epicrealismXL_vxviLastfameRealism.safetensors": {
        displayName: "epiCRealism XL | VXVI - LastFAME (Realism)",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: true,
        nsfw: true,
    },
    "SDXL/evalisenniaRealisticEastAsian_v30.safetensors": {
        displayName: "Evalisennia 伊岚: Realistic East Asian Female | 写实东亚女性人像 | v3.01",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: true,
        nsfw: true,
    },
    "SDXL/evermoreSDXL_v21NSFWFp16.safetensors": {
        displayName: "Evermore SDXL | v2.1 NSFW Fp16",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: true,
        nsfw: true,
    },
    "SDXL/fabledIllusionXXXLSFWNSFWPorn_v30PhotoNoir.safetensors": {
        displayName: "Fabled Illusion XXXL - (SFW / NSFW - Porn - Sex - Erotica - Fantasy - Art) | v3 Photo Noir",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: true,
        nsfw: true,
    },
    "SDXL/fasercore_xlV1.safetensors": {
        displayName: "FaserCore | XL_V1",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: true,
        nsfw: true,
    },
    "SDXL/fennfotoXL_v1.safetensors": {
        displayName: "fennfoto_XL | v1",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: true,
        nsfw: true,
    },
    "SDXL/FuchsiaXLPhoto_v10.safetensors": {
        displayName: "Fuchsia XL (Photo) | v10",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: true,
        nsfw: true,
    },
    "SDXL/galaxytimemachinesGTM_xlplusV35.safetensors": {
        displayName: 'GalaxyTimeMachine\'s GTM "XLPlus" | XLPlus_v3.5',
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: true,
        nsfw: true,
    },
    "SDXL/genieSDXLUnchained_v10.safetensors": {
        displayName: "Genie_SDXL_unchained | v1.0",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: true,
        nsfw: true,
    },
    "SDXL/jibMixRealisticXL_v160Aphrodite.safetensors": {
        displayName: "Jib Mix Realistic XL | v16.0 - Aphrodite",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: true,
        nsfw: true,
    },
    "SDXL/juggernautXL_juggXIByRundiffusion.safetensors": {
        displayName: "Juggernaut XL | Jugg_XI_by_RunDiffusion",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: true,
        nsfw: false,
    },
    "SDXL/lustifySDXLNSFW_oltFIXEDTEXTURES.safetensors": {
        displayName: "LUSTIFY! [SDXL NSFW checkpoint] | OLT (FIXED TEXTURES)",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: true,
        nsfw: true,
    },
    "SDXL/lustimix_.safetensors": {
        displayName: "LustiMix | LustiMix",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: true,
        nsfw: true,
    },
    "SDXL/mumixxl_v11.safetensors": {
        displayName: "MuMixXL | v1.1",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: true,
        nsfw: true,
    },
    "SDXL/photoart_V50.safetensors": {
        displayName: "PhotoArt | PhotoArt v5.0",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: true,
        nsfw: true,
    },
    "SDXL/photopediaXL_45.safetensors": {
        displayName: "PhotoPedia XL | 4.5",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: true,
        nsfw: true,
    },
    "SDXL/realismSDXLByStable_v60XL.safetensors": {
        displayName: "Realism_SDXL_By_Stable_Yogi | v6.0_XL",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: true,
        nsfw: true,
    },
    "SDXL/realisticLustXL_v05.safetensors": {
        displayName: "Realistic Lust [XL] | v0.5",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: true,
        nsfw: true,
    },
    "SDXL/realisticLustXL_v09.safetensors": {
        displayName: "Realistic Lust [XL] | v0.9",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: true,
        nsfw: true,
    },
    "SDXL/realisticStockPhoto_v20.safetensors": {
        displayName: "Realistic Stock Photo | v2.0",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: true,
        nsfw: true,
    },
    "SDXL/realphotosdxi_0.safetensors": {
        displayName: "RealPhotoSDXI | RealPhotoSDXI.0",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: true,
        nsfw: true,
    },
    "SDXL/sensuaxlV2_v20.safetensors": {
        displayName: "SensuaXL v2 | v2.0",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: true,
        nsfw: true,
    },
    "SDXL/stepDadsStashXLV2_v20.safetensors": {
        displayName: "Step Dads Stash XL V.2 | v2.0",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: true,
        nsfw: true,
    },
    "SDXL/talesOfDigitalDesireSFW_v21.safetensors": {
        displayName: "Tales of Digital Desire (SFW & NSFW & XXX) | v2.1",
        sampler: "lcm",
        scheduler: "exponential",
        lora: false,
        clip: true,
        clipskip: -2,
        steps: 10,
        cfg: 1,
        dmd2: true,
        nsfw: true,
    },
};

/**
 * Fungsi yang mengambil daftar checkpoint.
 *
 * @description Fungsi ini mengambil daftar checkpoint dari cache atau mengembalikan nilai default jika cache belum diisi.
 * @returns {string[]} Daftar checkpoint.
 */
// Checkpoints
function fetchCheckpointOptions() {
    if (checkpointCache.checkpoints) return checkpointCache.checkpoints;

    // Daftar checkpoint dasar
    const baseCheckpoints = [
        "---- Anime ----",
        "Anime/animagineXLV31_v31.safetensors",
        "Anime/autismmixSDXL_autismmixPony.safetensors",
        "Anime/nngmixXL_v42.safetensors",
        "---- DMD2 ----",
        "DMD2/asianRealismByStable_v10DMD2.safetensors",
        "DMD2/centerfold_versionXIDmd2.safetensors",
        "DMD2/cognitiveriver_illustriousV10.safetensors",
        "DMD2/epicrealismXL_vxviLastfameDMD2.safetensors",
        "DMD2/gonzalomoDMD_v11.safetensors",
        "DMD2/lustifySDXLNSFW_endgameDMD2.safetensors",
        "DMD2/neuralSoup_v10.safetensors",
        "DMD2/neuralStew_v10.safetensors",
        "DMD2/realismSDXLByStable_v60XLDMD2.safetensors",
        "DMD2/realustriousPonyXL_dmd.safetensors",
        "DMD2/sirenForge_v21OldeskoolAnalog.safetensors",
        "DMD2/splashedMixDMD_v40.safetensors",
        "DMD2/ultraRealisticBy_v10DMD2.safetensors",
        "DMD2/xxxRay_dmd2.safetensors",

        "---- Illustrious ----",
        "Illustrious/asianRealismByStable_v10FP16.safetensors",
        "Illustrious/babesIllustriousBy_v30BF16.safetensors",
        "Illustrious/cyberillustrious_v35.safetensors",
        "Illustrious/illustriousRealismBy_v10VAE.safetensors",
        "Illustrious/jedpointreal_v1ILVae.safetensors",
        "Illustrious/jibMixIllustrious_v20Revelation.safetensors",
        "Illustrious/otherworldIDXLSDXL_v10.safetensors",
        "Illustrious/perfection3DILXLIllustrious_v11.safetensors",
        "Illustrious/perfectionRealisticILXL_v22.safetensors",
        "Illustrious/pornmasterPro_realismILV1VAE.safetensors",
        "Illustrious/realCosplayerUNCEN_v10.safetensors",
        "Illustrious/realismFusion_v10.safetensors",
        "Illustrious/reallybiglust_hibridIllustrious.safetensors",
        "Illustrious/reallybiglust_v095LoraCompatible.safetensors",
        "Illustrious/redcraftCADSUpdatedMar11_illust3relustion.safetensors",
        "Illustrious/reijality_v10.safetensors",
        "Illustrious/shutter_v20.safetensors",

        "---- Pony ----",
        "Pony/asianRealismByStable_v10FP16.safetensors",
        "Pony/cyberrealisticPony_v90Alt2.safetensors",
        "Pony/fasercore_v30PonyFP16.safetensors",
        "Pony/fucktasticRealCheckpointPony_21.safetensors",
        "Pony/iniverseMixSFWNSFW_ponyRealGuofengV50C.safetensors",
        "Pony/likeRealityPonyBy_v20VAE",
        "Pony/novaRealityXL_v70.safetensors",
        "Pony/realDream_sdxlPony15.safetensors",
        "Pony/ultraRealisticBy_v10FP16.safetensors",

        "---- SDXL ----",
        "SDXL/1girlPrinter20_v10.safetensors",
        "SDXL/agxl_V2.safetensors",
        "SDXL/AiprealisticSDXLNSFW_v10.safetensors",
        "SDXL/annolustxl_v2.safetensors",
        "SDXL/beyondimaginationxl_v0005Fix.safetensors",
        "SDXL/biglust17_v17.safetensors",
        "SDXL/biglustydonutmixNSFW_v12.safetensors",
        "SDXL/boomerArtModelBAM_bamV2.safetensors",
        "SDXL/chirps_v1.safetensors",
        "SDXL/clarityXL_v20.safetensors",
        "SDXL/cyberprimeXL_v11.safetensors",
        "SDXL/cyberrealisticXL_v53.safetensors",
        "SDXL/d33psixSDXL_d33psixSDXL.safetensors",
        "SDXL/donutsdeliverymixV4_v4.safetensors",
        "SDXL/epicjoy_alpha.safetensors",
        "SDXL/epicjuggernautxl_vxvXI.safetensors",
        "SDXL/epicrealismXL_vxviLastfameRealism.safetensors",
        "SDXL/evalisenniaRealisticEastAsian_v30.safetensors",
        "SDXL/evermoreSDXL_v21NSFWFp16.safetensors",
        "SDXL/fabledIllusionXXXLSFWNSFWPorn_v30PhotoNoir.safetensors",
        "SDXL/fasercore_xlV1.safetensors",
        "SDXL/fennfotoXL_v1.safetensors",
        "SDXL/FuchsiaXLPhoto_v10.safetensors",
        "SDXL/galaxytimemachinesGTM_xlplusV35.safetensors",
        "SDXL/genieSDXLUnchained_v10.safetensors",
        "SDXL/jibMixRealisticXL_v160Aphrodite.safetensors",
        "SDXL/juggernautXL_juggXIByRundiffusion.safetensors",
        "SDXL/lustifySDXLNSFW_endgame.safetensors",
        "SDXL/lustifySDXLNSFW_oltFIXEDTEXTURES.safetensors",
        "SDXL/lustimix_.safetensors",
        "SDXL/mumixxl_v11.safetensors",
        "SDXL/photoart_V50.safetensors",
        "SDXL/photopediaXL_45.safetensors",
        "SDXL/realismSDXLByStable_v60XL.safetensors",
        "SDXL/realisticLustXL_v05.safetensors",
        "SDXL/realisticLustXL_v09.safetensors",
        "SDXL/realisticStockPhoto_v20.safetensors",
        "SDXL/realphotosdxi_0.safetensors",
        "SDXL/sensuaxlV2_v20.safetensors",
        "SDXL/stepDadsStashXLV2_v20.safetensors",
        "SDXL/talesOfDigitalDesireSFW_v21.safetensors",
    ];

    checkpointCache.checkpoints = baseCheckpoints.map((ckpt) => ckpt);
    return checkpointCache.checkpoints;
}

/**
 * Fungsi yang mengambil daftar sampler.
 *
 * @description Fungsi ini mengembalikan daftar sampler yang tersedia.
 * @returns {string[]} Daftar sampler.
 */
function fetchSamplerOptions() {
    return [
        "euler",
        "euler_cfg_pp",
        "euler_ancestral",
        "euler_ancestral_cfg_pp",
        "heun",
        "heunpp2",
        "dpm_2",
        "dpm_2_ancestral",
        "lms",
        "dpm_fast",
        "dpm_adaptive",
        "dpmpp_2s_ancestral",
        "dpmpp_2s_ancestral_cfg_pp",
        "dpmpp_sde",
        "dpmpp_sde_gpu",
        "dpmpp_2m",
        "dpmpp_2m_cfg_pp",
        "dpmpp_2m_sde",
        "dpmpp_2m_sde_gpu",
        "dpmpp_3m_sde",
        "dpmpp_3m_sde_gpu",
        "ddpm",
        "lcm",
        "ipndm",
        "ipndm_v",
        "deis",
        "res_multistep",
        "res_multistep_cfg_pp",
        "res_multistep_ancestral",
        "res_multistep_ancestral_cfg_pp",
        "gradient_estimation",
        "er_sde",
    ];
}

/**
 * Fungsi yang mengambil daftar scheduler.
 *
 * @description Fungsi ini mengembalikan daftar scheduler yang tersedia.
 * @returns {string[]} Daftar scheduler.
 */
function fetchSchedulerOptions() {
    return [
        "normal",
        "karras",
        "exponential",
        "sgm_uniform",
        "simple",
        "ddim_uniform",
        "beta",
        "linear_quadratic",
        "kl_optimal",
    ];
}
