const hairColours = [
    // Natural
    "black",
    "brunette/brown",
    "dark brown",
    "medium brown",
    "light brown",
    "blonde",
    "platinum blonde",
    "ash blonde",
    "honey blonde",
    "strawberry blonde",
    "red",
    "auburn",
    "copper red",
    "cherry red",
    "gray/silver",
    "white",
    // Fashion
    "lavender",
    "ombre",
    "balayage",
    "highlights/lowlights",
    "rose gold",
    "bronde",
    "mermaid",
    // Fantasy
    "icy blonde",
    "smoky gray",
    "mocha brown",
    "caramel highlights",
    "opal",
    // Techniques
    "root shadow",
    "color melt",
    "foilayage",
];

const hairStyles = [
    // Classic
    "bob",
    "pixie cut",
    "shag",
    "mullet",
    // Braided
    "french braid",
    "dutch braid",
    "fishtail braid",
    "boxer braids",
    "cornrows",
    "micro braids",
    "fulani braids",
    "goddess braids",
    "braid",
    // Updos
    "bun",
    "top knot",
    "chignon",
    "ballerina bun",
    "french twist",
    "victory roll",
    // Ponytails
    "high ponytail",
    "low ponytail",
    "bubble ponytail",
    "side ponytail",
    "half-up ponytail",
    // Layers
    "layered cut",
    "feathered",
    "beach waves",
    "sleek straight",
    "curly",
    // Bangs
    "blunt bangs",
    "side-swept bangs",
    "curtain bangs",
    "wispy bangs",
    "baby bangs",
    // Others
    "wolf cut",
    "fade",
    "space buns",
    "half-up half-down",
    "pineapple updo",
];

const hairAdjectives = ["long", "messy", "wet", "sleek", "voluminous", "tousled", "flowing", "textured"];

const rooms = [
    "bedroom",
    "living room",
    "bathroom",
    "shower",
    "kitchen",
    "hot tub",
    "balcony",
    "hotel room",
    "rooftop",
    "master suite",
    "jacuzzi room",
    "attic",
    "library",
    "wine cellar",
    "fireplace lounge",
    "private pool",
    "sauna",
    "sunroom",
    "loft",
    "candlelit bath",
    "penthouse suite",
    "secluded cabin",
    "massage room",
    "velvet lounge",
    "garden gazebo",
    "private terrace",
    "mirrored room",
    "art studio",
    "yacht cabin",
    "hidden nook",
    "church",
    "woods cottage",
    "dining room",
    "patio",
];
