const GeneralPresets = {
    "fantasy worlds": {
        label: "Fantasy Worlds",
        prompts: {
            1: "A majestic elven city intricately carved into the shimmering facets of a towering glowing crystal mountain, bathed in ethereal golden light, surrounded by swirling misty air infused with faint sparkles, adorned with delicate filigree bridges and ornate spires piercing the clouds, rendered in a highly detailed cinematic style with soft depth of field",
            2: "A dragon rider in mid-flight soaring over a desolate volcanic wasteland, jagged obsidian peaks piercing through fiery crimson skies, the dragon’s scales glinting with molten hues, rider in dynamic pose gripping a silver lance, dramatic shadows stretching across the scorched earth, smoke curling upward in thick tendrils",
            3: "A hidden forest glade illuminated by towering bioluminescent mushrooms emitting a soft teal glow, delicate fairy creatures with translucent wings dancing in a spiral, surrounded by whispering ferns and dew-kissed vines, painted in soothing pastel colors with a dreamlike haze and intricate organic textures",
            4: "A dark sorcerer cloaked in tattered black robes summoning a swirling portal of crackling purple energy in the crumbling stone hall of a ruined gothic castle, arcane symbols pulsing faintly on the walls, cobwebs swaying in an unseen breeze, the atmosphere thick with ominous shadows and a faint violet mist",
            5: "A surreal floating island suspended in a golden sunrise, cascading waterfalls spilling over its edges into an endless abyss, lush emerald greenery draping its rocky cliffs, populated by vibrant exotic birds, rendered with a fantastical perspective and hyper-detailed foliage under a radiant sky streaked with peach and amber",
            6: "A knight clad in ornate silver armor etched with intricate runes, standing resolute on a stormy battlefield facing a colossal stone golem with glowing amber eyes, lightning illuminating the rain-soaked ground littered with broken shields, epic in scale with towering dark clouds and a palpable sense of tension",
            7: "A mystical marketplace nestled in a desert oasis under a twilight sky, vibrant silks in jewel tones billowing in the warm breeze, glowing lanterns casting intricate patterns of light and shadow, a bustling crowd of robed merchants and curious travelers haggling over exotic spices and shimmering trinkets",
            8: "A frost-covered palace perched atop a jagged icy cliff, ruled by an ice queen in a flowing gown of pale blue silk, its halls adorned with shimmering icicles refracting prismatic light, the air crisp and still, rendered in regal elegance with crystalline textures and a serene yet commanding presence",
            9: "A weathered pirate ship with tattered sails navigating a cosmic sea of twinkling stars, its hull adorned with steampunk brass fittings and glowing pistons, cutting through shimmering waves of violet and indigo nebulae, the deck alive with the faint hum of machinery and the distant glow of a celestial horizon",
            10: "A labyrinthine dungeon carved from ancient stone, lit by faintly glowing emerald runes etched into the walls, skeletal warriors clad in rusted armor emerging from the shadows, their hollow eye sockets flickering with an eerie green fog, the air thick with dampness and the distant echo of dripping water",
        },
    },
    "sci-fi futures": {
        label: "Sci-Fi Futures",
        prompts: {
            1: "A sprawling cyberpunk cityscape at night, its skyline dominated by towering neon signs in electric blues and pinks, flying cars streaking through the rain-soaked air leaving trails of light, reflective streets shimmering with puddles, detailed with gritty urban textures and a dense, atmospheric haze",
            2: "A lone astronaut in a sleek white suit traversing a vast red desert on an alien planet, twin suns casting elongated shadows over cracked crimson terrain, jagged rock formations rising in the distance, the scene infused with a sense of isolation and wonder, rendered in hyper-realistic detail",
            3: "A futuristic megacorporation tower piercing through a sea of rolling gray clouds, its sleek chrome surface reflecting the faint glow of holographic billboards advertising in alien script, drones buzzing around its base, the design minimalist yet imposing with sharp angles and a cold, sterile aesthetic",
            4: "A chaotic robot rebellion unfolding in a dystopian factory, sparks flying from clashing metal limbs, the air thick with dark smoke and the acrid scent of burning circuits, towering machinery looming in the background, captured in gritty realism with rusted textures and a palpable sense of unrest",
            5: "A starship battle erupting in the depths of space, sleek vessels weaving through exploding nebulas of violet and orange, vibrant laser beams cutting through the void, debris floating in zero gravity, dynamic angles showcasing the chaos and beauty of cosmic warfare in stunning detail",
            6: "A biodome on a frozen moon, its transparent dome encasing a lush jungle of towering ferns and glowing alien flora, contrasting sharply with the icy, desolate exterior bathed in pale blue light, artificial suns casting warm beams through the canopy, rendered with intricate ecological textures",
            7: "A time traveler stepping into a retro-futuristic city blending 1950s Americana with advanced technology—chrome diners with hovering tables, vintage cars with anti-gravity engines, citizens in pinstripe suits wielding holographic devices, all bathed in warm sepia tones with a nostalgic yet futuristic glow",
            8: "A hacker immersed in a virtual reality matrix, surrounded by cascading streams of glowing green code forming fractal patterns, standing on surreal floating platforms of translucent glass, the air pulsing with digital distortions, rendered in a sleek, high-tech aesthetic with a dreamlike edge",
            9: "An android with a polished silver exoskeleton gazing melancholically at a crumbling Earth from orbit, the planet’s surface scarred with fissures and shrouded in ash, faint stars glimmering in the background, detailed textures of the android’s joints and the planet’s decay enhancing the somber mood",
            10: "A serene colony perched on the rings of a gas giant, its floating platforms of white stone connected by delicate bridges, pastel skies of lavender and peach swirling in the distance, minimalist architecture adorned with soft glowing lights, evoking a sense of peaceful isolation",
        },
    },
    "nature & landscapes": {
        label: "Nature & Landscapes",
        prompts: {
            1: "A serene lake encircled by cherry blossom trees in full bloom, their pink petals drifting gently onto the water’s surface, golden hour light casting a warm glow across gentle ripples, distant mountains faintly visible through a soft haze, rendered with intricate floral details",
            2: "A towering waterfall plunging into a misty pool within a dense tropical jungle, vines draping over moss-covered rocks, faint rainbows shimmering in the spray, vibrant greens dominating the palette, the air alive with the distant calls of exotic birds and the scent of wet earth",
            3: "A snowy mountain peak piercing the heavens under a vibrant aurora borealis, waves of green and purple dancing across a starry sky, the air crisp and biting, ice crystals glinting on the slopes, captured in a breathtaking panoramic view with a crystalline sheen",
            4: "A vast desert dune sculpted by the wind at sunset, warm oranges and purples bleeding into the sky, long shadows stretching across rippling sand, a lone cactus silhouetted on the horizon, rendered with hyper-detailed textures of the grains and a tranquil stillness",
            5: "A rugged coastal cliff battered by crashing waves, stormy skies roiling with dark gray clouds, jagged rocks glistening with sea spray, dramatic lighting casting stark contrasts, the scene alive with the roar of the ocean and the scent of salt in the air",
            6: "A tranquil bamboo forest with towering stalks swaying gently in a soft fog, a hidden wooden shrine adorned with moss and lanterns nestled at its heart, muted earth tones dominating the palette, intricate details of the bamboo’s texture and the shrine’s weathered wood",
            7: "A vast savannah stretching to a hazy horizon, golden grass rippling in the breeze, a herd of giraffes grazing beneath scattered acacia trees, the sky a brilliant cerulean with faint wisps of cloud, captured in a warm, expansive realism with detailed animal anatomy",
            8: "A volcanic island rising from the sea, its black sand beaches glistening under the glow of winding lava rivers, smoky air curling upward from glowing fissures, the ocean reflecting the fiery hues, rendered with stark contrasts and intricate geological textures",
            9: "A sprawling meadow bursting with wildflowers in every hue—lavender, crimson, and gold—butterflies with iridescent wings fluttering amid the blooms, bright midday sun casting soft shadows, detailed petals and delicate insect wings creating a vibrant, lively scene",
            10: "A frozen tundra stretching endlessly under a pale sky, a lone polar bear trudging through powdery snow, icy blues dominating the palette, subtle sunlight reflecting off crystalline ice patches, the air heavy with silence and the faint crunch of snow underfoot",
        },
    },
    "historical eras": {
        label: "Historical Eras",
        prompts: {
            1: "A Roman gladiator arena in the heat of battle, muscular warriors clashing with glinting swords and shields, roaring crowds in tiered stone stands, dust swirling in the air under a blazing sun, detailed with the texture of worn armor and the intensity of combat",
            2: "A medieval village festival in full swing, colorful banners fluttering above thatched cottages, peasants in rough-spun tunics dancing around a maypole, warm lighting from bonfires casting flickering shadows, the air rich with the scent of roasted meat and ale",
            3: "A grand Victorian ballroom aglow with soft candlelight from ornate chandeliers, women in elegant gowns of silk and lace twirling with men in tailcoats, intricate parquet floors reflecting the glow, detailed with the opulence of the era and a refined, romantic atmosphere",
            4: "An ancient Egyptian tomb illuminated by flickering torchlight, its walls adorned with hieroglyphs and golden treasures—scarabs, urns, and jeweled sarcophagi—dust motes floating in the stale air, shadows dancing across the stone, rendered with archaeological precision",
            5: "A samurai duel at dawn on a misty hilltop, cherry blossoms falling gently around two warriors in lacquered armor, their katanas poised mid-strike, the air thick with tension and the faint scent of dew, captured in sharp detail with a cinematic sense of grace and danger",
            6: "A raucous pirate tavern on a stormy night, its wooden interior creaking under the wind, rowdy sailors in eye patches and tricorn hats clashing mugs of rum, flickering lanterns casting warm light over scarred tables, detailed with the texture of weathered wood and a lively chaos",
            7: "A Renaissance painter’s studio bathed in warm sunlight streaming through a tall window, rich oil paints in earthy hues smeared across a canvas of a detailed still life—ripe fruit, velvet cloth, and a silver goblet—brushes and palettes scattered across a worn wooden table",
            8: "A Viking longship cutting through icy fjords, its dragon-headed prow piercing the mist, rugged warriors in furs and helmets rowing with grim determination, overcast skies casting a cold, pale light over jagged cliffs, rendered with the raw power of the sea and detailed textures",
            9: "A 1920s speakeasy hidden behind a brick wall, jazz musicians in pinstripe suits playing sultry tunes on saxophone and piano, smoky air curling around flappers in beaded dresses, art deco chandeliers casting a golden glow, detailed with the decadence and secrecy of the era",
            10: "A Wild West showdown at high noon on a dusty street flanked by wooden saloons, two gunslingers in wide-brimmed hats facing off with hands hovering over holsters, tumbleweeds rolling in the dry wind, sepia tones enhancing the tension and gritty realism of the scene",
        },
    },
    "surreal dreams": {
        label: "Surreal Dreams",
        prompts: {
            1: "A massive clock with molten gold hands dripping over the edge of a floating cubic monolith, suspended in an endless void of swirling pastel gradients—lavender, peach, and mint—time itself bending and warping, rendered with smooth, dreamlike transitions and a glossy sheen",
            2: "A giant iridescent fish swimming through a sky of fluffy white clouds tinged with vibrant blues, its scales refracting light like prisms, leaving a trail of shimmering bubbles, the scene whimsical yet serene, detailed with the texture of water and the softness of vapor",
            3: "A humanoid figure sculpted from countless twinkling stars walking across a glassy sea that reflects an infinite cosmos, each step rippling with cosmic dust, the air alive with a faint hum of celestial energy, rendered with intricate stellar patterns and a hypnotic glow",
            4: "A gnarled tree growing upside down from the surface of a glowing crescent moon, its twisted roots stretching into a starry void, an eerie greenish luminescence emanating from its bark, detailed with surreal distortions and a haunting, otherworldly beauty",
            5: "A sprawling city where towering buildings double as giant musical instruments—flutes, violins, and drums—emitting vibrant soundwaves that ripple through the air in hues of gold and crimson, abstract art come to life with intricate architectural details and a pulsating rhythm",
            6: "A towering mirror standing alone in a barren wasteland, its fractured surface reflecting a lush, alien world of towering purple flora and crimson skies, shards of glass floating around it, surreal colors bleeding into one another with a delicate, unsettling realism",
            7: "A colossal eye hovering in a desert of golden sand, its iris a swirling vortex of blues and greens, winds whipping the dunes into spiraling patterns around it, the scene unsettling yet mesmerizing, detailed with the texture of sand and the intensity of its gaze",
            8: "A spiraling staircase of glowing white marble twisting downward into a starry abyss, each step pulsing faintly with light, surrounded by a dreamlike haze of indigo and violet, rendered with smooth curves and an infinite depth that draws the eye endlessly downward",
            9: "A single flower with petals of deep crimson blooming into a sprawling galaxy, its edges fading into swirling nebulae of purple and blue, stardust drifting from its core, intricate details of the petals merging seamlessly with the cosmic expanse",
            10: "A shadowy figure cloaked in darkness painting the sky with sweeping strokes of radiant rainbows, its silhouette stark against the vivid hues of red, yellow, and violet, the air shimmering with prismatic light, detailed with the contrast of shadow and color",
        },
    },
    "steampunk adventures": {
        label: "Steampunk Adventures",
        prompts: {
            1: "A majestic steam-powered airship drifting over a Victorian city of red brick and iron spires, its hull adorned with polished brass gears and pistons hissing steam, cloudy skies tinged with soot, detailed with intricate mechanical textures and a warm, industrial glow",
            2: "A towering clockwork dragon with articulated wings of copper and steel, exhaling plumes of white steam, its glowing red eyes piercing through a foggy twilight, intricate machinery whirring within its chest, rendered with a blend of organic and mechanical detail",
            3: "A bustling steampunk market in a cobblestone square, vendors in leather goggles hawking wares beneath a canopy of copper pipes and ticking clocks, vibrant silks and brass trinkets catching the warm light, the air alive with the clatter of gears and the scent of oil",
            4: "A steam locomotive thundering through a narrow desert canyon, billowing thick smoke from its ornate smokestack, its retro-futuristic design featuring riveted plates and glowing gauges, the arid landscape streaked with red rock and dust, captured in dynamic motion",
            5: "A mad inventor’s cluttered lab illuminated by the crackling arcs of twin Tesla coils, shelves overflowing with sparking gadgets and blueprints, the air buzzing with electricity, detailed with the chaos of scattered tools and the dramatic interplay of light and shadow",
            6: "A massive mechanical whale breaching an industrial sea of churning gray waves, its rusted hull creaking as steam vents hiss along its spine, stormy skies flashing with lightning, rendered with the weight of metal and the wild energy of the ocean",
            7: "A steampunk duelist in a top hat and leather coat wielding a steam-powered pistol, standing on a foggy cobblestone street lined with gas lamps, the weapon emitting a faint hiss, detailed with the texture of worn leather and the moody ambiance of the scene",
            8: "A floating city suspended by enormous whirring propellers, its ornate architecture of brass and glass glowing in the golden dusk, streets bustling with citizens in Victorian attire, the sky streaked with soft oranges, rendered with a sense of grandeur and motion",
            9: "A steampunk explorer with a mechanical arm traversing a dense jungle, overgrown ruins of stone temples peeking through the foliage, the arm’s pistons gleaming with dew, detailed with the contrast of nature’s chaos and the precision of machinery",
            10: "A grand clock tower dominating a foggy skyline, its exposed gears ticking loudly in a hypnotic rhythm, the face illuminated by a moody twilight glow, intricate ironwork framing the structure, the scene rich with the texture of metal and the weight of time",
        },
    },
    "horror & dark themes": {
        label: "Horror & Dark Themes",
        prompts: {
            1: "A haunted mansion looming on a jagged hill, its cracked windows flickering with ghostly candlelight, cobwebs draping the warped wooden porch, shadowy figures peering from behind tattered curtains, the air thick with a damp chill and the scent of decay",
            2: "A desolate graveyard bathed in the crimson glow of a blood-red moon, skeletal hands clawing through the cracked earth, thick fog curling around weathered tombstones, detailed with the texture of bone and the eerie stillness of the night",
            3: "A twisted forest of gnarled, leafless trees stretching into a pitch-black sky, their branches clawing at the air, glowing yellow eyes watching from the shadows, an eerie green light seeping from the ground, rendered with a sense of dread and organic decay",
            4: "A sinister clown standing alone in the ruins of an abandoned carnival, its cracked makeup peeling to reveal a grotesque grin, a rusted Ferris wheel creaking in the background, the air heavy with the scent of mildew and the faint echo of laughter",
            5: "A ghostly shipwreck rising from a turbulent ocean, its tattered sails flapping in the stormy wind, jagged timbers glowing faintly with an unearthly blue light, lightning illuminating the skeletal remains of the crew, detailed with the chaos of the sea and supernatural dread",
            6: "A vampire lord seated on a throne of black stone in a gothic castle, his crimson cape pooling like blood on the floor, the candlelit throne room adorned with stained glass casting eerie shadows, his piercing gaze and sharp fangs rendered in chilling detail",
            7: "A hulking werewolf howling atop a snowy ridge, its matted fur streaked with blood, the full moon casting a silver glow over a forest of skeletal trees, crimson stains dotting the snow, detailed with the ferocity of the beast and the stark winter landscape",
            8: "A cursed mirror in a dark, dusty room reflecting a decaying face with hollow eyes, the glass cracked and oozing a faint black mist, the air heavy with the scent of rot, rendered with unsettling realism and the texture of weathered wood and glass",
            9: "A swarm of bats coalescing into a towering human silhouette against a moonlit sky, their wings rustling like whispers, the figure’s eyes glowing faintly red, the scene chilling with its fluid motion and the interplay of shadow and light",
            10: "An ancient well of damp, moss-covered stone, glowing tendrils of pale green light snaking upward from its depths, the air thick with the sound of dripping water and a faint, unnatural hum, detailed with the ominous texture of the stone and the creeping unknown",
        },
    },
    "everyday life": {
        label: "Everyday Life",
        prompts: {
            1: "A cozy coffee shop on a rainy day, its fogged-up windows glowing with warm amber light, steam curling from ceramic cups of rich espresso, patrons in scarves reading books at wooden tables, detailed with the texture of raindrops and the comfort of the interior",
            2: "A bustling farmer’s market in the crisp autumn air, stalls overflowing with vibrant pumpkins, apples, and golden corn, vendors in aprons calling out to a crowd wrapped in coats, leaves skittering across the cobblestone, rendered with lively detail and seasonal warmth",
            3: "A child in a bright red jacket flying a kite in a windswept field, the kite’s tail of rainbow ribbons dancing against a brilliant blue sky, grass bending in the breeze, the scene alive with dynamic motion and the innocence of play",
            4: "A street musician in a worn coat playing a violin on a cobblestone path, the golden sunset casting long shadows, notes drifting through the air as passersby drop coins into an open case, detailed with the texture of stone and the glow of fading light",
            5: "A quiet library with towering bookshelves of dark wood stretching to a vaulted ceiling, soft sunlight streaming through stained glass windows, dust motes floating in the beams, an elderly reader hunched over a tome, rendered with the stillness and texture of old paper",
            6: "A family picnic by a lazy river, a checkered blanket spread with baskets of bread and fruit, children splashing at the water’s edge, vibrant summer colors of green grass and blue sky, detailed with the warmth of togetherness and the ripple of water",
            7: "A skateboarder in ripped jeans performing a mid-air trick in an urban park, graffiti-covered concrete ramps in the background, the air buzzing with the energy of youth, captured in sharp detail with the texture of worn pavement and a vibrant city vibe",
            8: "A baker in a flour-dusted apron kneading dough in a rustic kitchen, wooden beams overhead, shelves lined with jars of spices and fresh herbs, warm tones of golden bread rising in the oven, detailed with the tactile feel of flour and the scent of yeast",
            9: "A fluffy dog chasing its tail in a lush backyard, blades of grass bending under its paws, a wooden fence weathered by time in the background, the playful mood enhanced by the bright sunlight and the texture of fur and earth",
            10: "A night market bustling with food stalls under glowing neon signs, steam rising from woks of sizzling noodles, a lively crowd in colorful jackets haggling over trinkets, the air rich with the aroma of spices and the hum of conversation",
        },
    },
    "mythical creatures": {
        label: "Mythical Creatures",
        prompts: {
            1: "A phoenix rising triumphantly from a bed of glowing ashes, its fiery wings spread wide with feathers of crimson and gold, embers spiraling upward in the smoky air, the scene dramatic with the intensity of rebirth and intricate detailing of its plumage",
            2: "A mermaid lounging on a jagged rocky shore, her shimmering scales of teal and violet catching the light, long hair tangled with seashells, the stormy sea crashing behind her, detailed with the texture of water and the wild beauty of the ocean",
            3: "A centaur archer poised in a moonlit forest clearing, his muscular equine body gleaming with sweat, bowstring taut as he aims at an unseen target, cherry blossoms drifting in the misty air, rendered with the grace of motion and detailed anatomy",
            4: "A griffin with majestic feathers of white and gold soaring over snow-capped peaks, its eagle talons glinting in the crisp air, wings cutting through wisps of cloud, the scene expansive with the texture of fur and the chill of high altitude",
            5: "A unicorn with a pearlescent horn drinking from a glowing stream in misty woods, its mane flowing like silk, ethereal light bathing the scene in soft whites and silvers, detailed with the delicacy of its form and the serenity of the forest",
            6: "A kraken emerging from the inky depths of the ocean, its massive tentacles coiling around a sinking ship, turbulent waves crashing under a stormy sky, the beast’s eyes glowing faintly yellow, rendered with the power of the sea and intricate suction-cup textures",
            7: "A sphinx crouched atop a sun-scorched dune guarding an ancient ruin, its lion body carved with muscle, golden sand swirling around its enigmatic face, piercing gaze fixed ahead, detailed with the weight of stone and the mystery of its presence",
            8: "A nine-tailed fox standing in a bamboo grove, its glowing tails of silver and blue fanning out like a celestial aura, misty air curling around the stalks, the scene mystical with the softness of fur and the sharpness of bamboo",
            9: "A minotaur looming in a torchlit labyrinth, its hulking frame adorned with scars, horns glinting in the flickering light, a menacing stance as it grips a rusted axe, detailed with the texture of stone walls and the primal ferocity of the beast",
            10: "A pegasus landing gracefully on a fluffy cloud at sunrise, its wings of pure white folding against its sleek body, the sky radiant with pinks and golds, the scene serene with the softness of feathers and the vastness of the heavens",
        },
    },
    "abstract art": {
        label: "Abstract Art",
        prompts: {
            1: "A swirling vortex of neon colors—electric pink, lime green, and cobalt blue—forming the faint outline of a human silhouette against a stark black background, vibrant energy pulsing through the curves, rendered with smooth gradients and a glossy, luminous finish",
            2: "A fractured cube of translucent glass floating in a boundless sea of radiant light, its sharp edges refracting prismatic hues of violet and gold, surreal gradients bleeding into the void, detailed with the interplay of reflection and infinite depth",
            3: "A crashing wave of geometric shapes—triangles, circles, and hexagons—in bold reds and blues colliding in chaotic harmony, the flow dynamic and forceful, the scene alive with the texture of edges and the rhythm of abstract motion",
            4: "A spiraling helix of golden threads weaving through a starry expanse, each strand shimmering with a metallic sheen, converging at a glowing core of pure white light, intricate patterns unfolding into infinite depth with a cosmic elegance",
            5: "A kaleidoscope of countless eyes arranged in shifting, hypnotic patterns, their irises muted in shades of gray and taupe, staring from a canvas of soft shadows, unsettling yet captivating, detailed with the realism of pupils and the fluidity of form",
            6: "A boundless field of floating spheres pulsing with soft pastel light—peach, mint, and lavender—arranged in a minimalist grid, their surfaces smooth and reflective, the scene serene with subtle glows and a delicate sense of weightlessness",
            7: "A single jagged line of stark white cutting through a canvas of twinkling stars, the contrast stark and piercing, cosmic dust trailing in its wake, the scene bold with the texture of the void and the simplicity of its disruption",
            8: "A melting grid of warm hues—amber, crimson, and ochre—dripping downward in viscous streams, the chaos abstract yet deliberate, the canvas alive with the texture of liquid and the weight of gravity pulling it apart",
            9: "A symphony of curved lines dancing in perfect unison, their surfaces gleaming with a metallic sheen of silver and bronze, the air shimmering with a futuristic glow, detailed with the precision of form and the harmony of motion",
            10: "A void filled with overlapping shadows in a monochromatic palette of deep grays, subtle textures of smoke and silk emerging from the darkness, the scene minimalist yet rich with depth, evoking a quiet, contemplative stillness",
        },
    },
};
