"""Mimpi Dashboard — Z-Image Models Registry"""

# ── Z-Image Models Registry ──
ZIMAGE_CHECKPOINTS: list[dict] = [
    {"name": "2127ZImageAsianUtopian_v36TurboFFV", "file": "2127ZImageAsianUtopian_v36TurboFFV.safetensors"},
    {"name": "beyondREALITY_V30", "file": "beyondREALITY_V30.safetensors"},
    {"name": "bigLove_zt3", "file": "bigLove_zt3.safetensors"},
    {"name": "copaxTimeless_xplusZ13", "file": "copaxTimeless_xplusZ13.safetensors"},
    {"name": "cyberrealisticZImage_v50", "file": "cyberrealisticZImage_v50.safetensors"},
    {"name": "darkBeast_darkblitz6Beyondnsfw", "file": "darkBeast_darkblitz6Beyondnsfw.safetensors"},
    {"name": "darkBeast_darkblitzZIT5steps", "file": "darkBeast_darkblitzZIT5steps.safetensors"},
    {"name": "divingZImageTurbo_v60Fp16", "file": "divingZImageTurbo_v60Fp16.safetensors"},
    {"name": "gonzalomoZpop_v40", "file": "gonzalomoZpop_v40.safetensors"},
    {"name": "intorealism_zitV50", "file": "intorealism_zitV50.safetensors"},
    {"name": "jibMixZIT_v20", "file": "jibMixZIT_v20.safetensors"},
    {"name": "moodyProMix_zitV12DPO", "file": "moodyProMix_zitV12DPO.safetensors"},
    {"name": "moodyProMix_zitV13", "file": "moodyProMix_zitV13.safetensors"},
    {"name": "pornmasterZImage_baseV1", "file": "pornmasterZImage_baseV1.safetensors"},
    {"name": "pornmasterZImage_turboV35Bf16", "file": "pornmasterZImage_turboV35Bf16.safetensors"},
    {"name": "realDream_zitV6", "file": "realDream_zitV6.safetensors"},
    {"name": "redcraftERNIERedmix_redzit15AIO", "file": "redcraftERNIERedmix_redzit15AIO.safetensors"},
    {"name": "unstablebastard_7", "file": "unstablebastard_7.safetensors"},
    {"name": "unstablebastard_v9", "file": "unstablebastard_v9.safetensors"},
    {"name": "unstableRevolution_V3Fp16", "file": "unstableRevolution_V3Fp16.safetensors"},
    {"name": "zImageTurboNSFW_90", "file": "zImageTurboNSFW_90.safetensors"},
    {"name": "zimageTurboNSFWBy_2602NSFWBF16", "file": "zimageTurboNSFWBy_2602NSFWBF16.safetensors"},
    {"name": "zit_v11", "file": "zit_v11.safetensors"},
    {"name": "beyondREALITY_30FP8", "file": "FP8/beyondREALITY_30FP8.safetensors"},
    {"name": "intorealismZITAsian_v20FP8", "file": "FP8/intorealismZITAsian_v20FP8.safetensors"},
    {"name": "moodyProMix_zitV12DPOFP8", "file": "FP8/moodyProMix_zitV12DPOFP8.safetensors"},
    {"name": "pornmasterZImage_turboV35Fp8", "file": "FP8/pornmasterZImage_turboV35Fp8.safetensors"},
    {"name": "unstablebastard_v9_fp8", "file": "FP8/unstablebastard_v9_fp8.safetensors"},
    {"name": "zImageTurboNSFW_82BF16FP8", "file": "FP8/zImageTurboNSFW_82BF16FP8.safetensors"},
    {"name": "zimageTurboNSFWBy_2602NSFWFP8", "file": "FP8/zimageTurboNSFWBy_2602NSFWFP8.safetensors"},
]

ZIMAGE_LORAS: list[str] = [
    "anal.safetensors",
    "b3tterbreast.safetensors",
    "b3tternud3s_v3.safetensors",
    "blowjob.safetensors",
    "cowgirl.safetensors",
    "cum on body Z.safetensors",
    "cum.safetensors",
    "deedee_amateur_photography_zimage_base_and_turbo_v1.safetensors",
    "doggy style.safetensors",
    "famegrid_spice_v2_z_image_fp32.safetensors",
    "gp-zimage_000008000.safetensors",
    "gta6_amateur_photography_zimagebase_v2.safetensors",
    "Hands + Feet + skin perfection style zib v1.safetensors",
    "Hands + Feet + skin v1.1.safetensors",
    "hina_zImageTurbo_asianMix_v4.57-bf16.safetensors",
    "hina_zImageTurbo_asianMix_v4.59C-bf16.safetensors",
    "Kook_Zimage_Turbo.safetensors",
    "lenovo_z.safetensors",
    "lenovo_zimagebase.safetensors",
    "m99_labiaplasty_pussy_6_zimage.safetensors",
    "missionary.safetensors",
    "Mystic-XXX-ZIT-V4.safetensors",
    "Mystic-XXX-ZIT-V5.safetensors",
    "Mystic-XXX-ZIT-V6.safetensors",
    "Mystic-XXX-ZIT-V7.safetensors",
    "NIceAsians_Zimage.safetensors",
    "nicegirls_zimagebase.safetensors",
    "NSFW_master_ZIT_000017532.safetensors",
    "nude_000100000.safetensors",
    "PornMaster_bukkake_zimage_v2_B.safetensors",
    "PornMaster_NSFW_ZIT_V1.safetensors",
    "PornMaster_pov_oral_sex_zimage_v1_lora_B.safetensors",
    "pussy-zimage-v1_000026000.safetensors",
    "RealisticSnapshot-Zimage-Turbov5.safetensors",
    "REDZ15_DetailDaemonZ_lora_v1.1.safetensors",
    "reverse cowgirl.safetensors",
    "skin texture Photorealistic style v4.5.safetensors",
    "skin texture style zib v1.1.safetensors",
    "skin texture style zib v2.1.safetensors",
    "Softmute_SoloLoRA_ZIBv1.safetensors",
    "Spooning Position.safetensors",
    "spread pussy v2.safetensors",
    "stand and Carry.safetensors",
    "TeeKaysTittyTime_AQueensTits_V1-2_ZIT.safetensors",
    "tits job.safetensors",
    "TurboPussyZ_v2.safetensors",
    "Z-Image-fac1al.safetensors",
    "Z-Real-v1.0.safetensors",
    "Zed_Turbo_Lightning.safetensors",
    "zit_sda_v1.safetensors",
]
