// Cached Checkpoints
const checkpointCache = {};

// Checkpoints Maps
// Checkpoints Maps
const checkpointNameMapping = {
    "Illustrious/cyberillustrious_v30.safetensors": { displayName: "CyberIllustrious V30", sampler: "dpmpp_2m_sde_gpu" },
    "Illustrious/novaRealityXL_illustriousV20.safetensors": { displayName: "NovaRealityXL V20", sampler: "dpmpp_2m_sde_gpu" },
    "Illustrious/perfectionRealisticILXL_v12.safetensors": {
        displayName: "Perfection Realistic V1.2",
        sampler: "dpmpp_2m_sde_gpu",
    },
    "Illustrious/realismIllustriousBy_v30FP16.safetensors": {
        displayName: "RealismIllustrious V30",
        sampler: "dpmpp_2m_sde_gpu",
    },
    "Illustrious/redcraftCADSUpdatedMar11_illust3relustion.safetensors": {
        displayName: "RedcraftCADS Mar11",
        sampler: "dpmpp_2m_sde_gpu",
    },
    "Illustrious/rillusmRealistic_v20.safetensors": { displayName: "RillusmRealistic V20", sampler: "dpmpp_2m_sde_gpu" },
    "Pony/3xthreat2kModelThatUsesPONY_v10.safetensors": { displayName: "3xThreat2k V10", sampler: "dpmpp_2m_sde_gpu" },
    "Pony/babesByStableYogi_ponyV4VAEFix.safetensors": { displayName: "BabesByStableYogi V4", sampler: "dpmpp_2m_sde_gpu" },
    "Pony/cyberrealisticPony_v85.safetensors": { displayName: "CyberRealisticPony V85", sampler: "dpmpp_2m_sde_gpu" },
    "Pony/fasercore_v30PonyFP16.safetensors": { displayName: "Fasercore V30", sampler: "dpmpp_2m_sde_gpu" },
    "Pony/fucktasticRealCheckpointPony_21.safetensors": {
        displayName: "Fucktastic Real Checkpoint V2.1",
        sampler: "dpmpp_2m_sde_gpu",
    },
    "Pony/iniverseMixSFWNSFW_ponyRealGuofengV50C.safetensors": { displayName: "IniverseMix V50C", sampler: "dpmpp_2m_sde_gpu" },
    "Pony/ponyDiffusionV6XL.safetensors": { displayName: "PonyDiffusion V6XL", sampler: "dpmpp_2m_sde_gpu" },
    "Pony/pornyPonyByStable_v20FP16.safetensors": { displayName: "PornyPony V20", sampler: "dpmpp_2m_sde_gpu" },
    "Pony/realDream_sdxlPony15.safetensors": { displayName: "RealDream Pony15", sampler: "dpmpp_2m_sde_gpu" },
    "Pony/realismByStableYogi_v40FP16.safetensors": { displayName: "RealismByStableYogi V40", sampler: "dpmpp_2m_sde_gpu" },
    "Pony/uberRealisticPornMergePonyxl_ponyxlHybridV1.safetensors": {
        displayName: "UberRealisticPornMerge V1",
        sampler: "dpmpp_2m_sde_gpu",
    },
    "SDXL/acornIsBoningXL_xlV2.safetensors": { displayName: "AcornIsBoningXL V2", sampler: "dpmpp_2m_sde_gpu" },
    "SDXL/agxl_V2.safetensors": { displayName: "AGXL V2", sampler: "dpmpp_2m_sde_gpu" },
    "SDXL/animaPencilXL_v500.safetensors": { displayName: "AnimaPencilXL V500", sampler: "dpmpp_2m_sde_gpu" },
    "SDXL/annolustxl_v2.safetensors": {
        displayName: "ANNOLustXL v2",
        sampler: "dpmpp_2m_sde_gpu",
    },
    "SDXL/babesByStableYogi_v4XLFP16.safetensors": { displayName: "BabesByStableYogi V4XL", sampler: "dpmpp_2m_sde_gpu" },
    "SDXL/bestPornMergeBPM_v10.safetensors": { displayName: "BestPornMergeBPM v10 V4XL", sampler: "dpmpp_2m_sde_gpu" },
    "SDXL/biglovexl2.wBWt.safetensors": { displayName: "BigLoveXL2", sampler: "dpmpp_2m_sde_gpu" },
    "SDXL/biglust16.kst6.safetensors": { displayName: "BigLust16", sampler: "dpmpp_2m_sde_gpu" },
    "SDXL/boomerArtModelBAM_bamV2.safetensors": { displayName: "BoomerArtModel V2", sampler: "dpmpp_2m_sde_gpu" },
    "SDXL/clarityXL_v20.safetensors": { displayName: "ClarityXL V20", sampler: "dpmpp_2m_sde_gpu" },
    "SDXL/cyberprimeXL_v10.safetensors": {
        displayName: "Cyberprime XL v1.0",
        sampler: "dpmpp_2m_sde_gpu",
    },
    "SDXL/cyberrealisticXL_v5.safetensors": { displayName: "CyberRealisticXL V5", sampler: "dpmpp_2m_sde_gpu" },
    "SDXL/d33psixSDXL_d33psixSDXL.safetensors": {
        displayName: "D33PSIX (dpmpp_2m/karras, 35, 3.5, CLIP Skip 2)",
        sampler: "dpmpp_2m_sde_gpu",
    },
    "SDXL/epicrealismXL_vxvAnewstoryRealism.safetensors": {
        displayName: "EpicRealismXL VxV AnewstoryRealism",
        sampler: "dpmpp_2m_sde_gpu",
    },
    "SDXL/epicrealismXL_vxviLastfameRealism.safetensors": {
        displayName: "EpicRealismXL VxV LastfameRealism",
        sampler: "dpmpp_2m_sde_gpu",
    },
    "SDXL/fasercore_xlV1.safetensors": { displayName: "Fasercore XL V1", sampler: "dpmpp_2m_sde_gpu" },
    "SDXL/jibMixRealisticXL_v160Aphrodite.safetensors": { displayName: "JibMixRealisticXL V160", sampler: "dpmpp_2m_sde_gpu" },
    "SDXL/juggernautXL_juggXIByRundiffusion.safetensors": { displayName: "JuggernautXL XI", sampler: "dpmpp_2m_sde_gpu" },
    "SDXL/leosamsHelloworldXL_helloworldXL70.safetensors": { displayName: "HelloworldXL V70", sampler: "dpmpp_2m_sde_gpu" },
    "SDXL/lustifySDXLNSFW_endgame.safetensors": { displayName: "LustifySDXL Endgame", sampler: "dpmpp_2m_sde_gpu" },
    "SDXL/lustifySDXLNSFW_oltONELASTTIME.safetensors": { displayName: "LustifySDXL OLT", sampler: "dpmpp_2m_sde_gpu" },
    "SDXL/lustimix_.safetensors": { displayName: "Lustimix", sampler: "dpmpp_2m_sde_gpu" },
    "SDXL/lustimix_big.safetensors": { displayName: "Lustimix Big", sampler: "dpmpp_2m_sde_gpu" },
    "SDXL/lustimix_bigRebirth.safetensors": { displayName: "Lustimix Big Rebirth", sampler: "dpmpp_2m_sde_gpu" },
    "SDXL/mumixxl_v11.safetensors": {
        displayName: "MuMixXL v1.1 (dpmpp_2m/karras, 35, 4.5, No CLIP Skip)",
        sampler: "dpmpp_2m_sde_gpu",
    },
    "SDXL/msSDXLRealV3_v3.safetensors": { displayName: "MSSDXLReal V3", sampler: "dpmpp_2m_sde_gpu" },
    "SDXL/novaRealityXL_v70.safetensors": { displayName: "NovaRealityXL V70", sampler: "dpmpp_2m_sde_gpu" },
    "SDXL/omnigenxlNSFWSFW_v10.safetensors": { displayName: "OmnigenXL V10", sampler: "dpmpp_2m_sde_gpu" },
    "SDXL/perfectionRealisticILXL_v10.safetensors": { displayName: "PerfectionRealisticILXL V10", sampler: "dpmpp_2m_sde_gpu" },
    "SDXL/photoart_V40.safetensors": { displayName: "PhotoArt", sampler: "dpmpp_2m_sde_gpu" },
    "SDXL/photopediaXL_45.safetensors": { displayName: "PhotopediaXL V45", sampler: "dpmpp_2m_sde_gpu" },
    "SDXL/polyhedronSDXL_v3.safetensors": { displayName: "PolyhedronSDXL V3", sampler: "dpmpp_2m_sde_gpu" },
    "SDXL/pornmaster_proSDXLV3VAE.safetensors": { displayName: "Pornmaster ProSDXL V3", sampler: "dpmpp_2m_sde_gpu" },
    "SDXL/realismByStableYogi_v5XLFP16.safetensors": { displayName: "RealismByStableYogi V5XL", sampler: "dpmpp_2m_sde_gpu" },
    "SDXL/realismEngineSDXL_v30VAE.safetensors": { displayName: "RealismEngineSDXL V30", sampler: "dpmpp_2m_sde_gpu" },
    "SDXL/realisticLustXL_v05.safetensors": { displayName: "RealisticLustXL V05", sampler: "dpmpp_2m_sde_gpu" },
    "SDXL/realisticStockPhoto_v20.safetensors": { displayName: "RealisticStockPhoto V20", sampler: "dpmpp_2m_sde_gpu" },
    "SDXL/realvisxlV50_v50Bakedvae.safetensors": { displayName: "RealvisXL V50", sampler: "dpmpp_2m_sde_gpu" },
    "SDXL/sd_xl_base_1.0_0.9vae.safetensors": { displayName: "SDXL Base 1.0", sampler: "dpmpp_2m_sde_gpu" },
    "SDXL/sd_xl_refiner_1.0.safetensors": { displayName: "SDXL Refiner 1.0", sampler: "dpmpp_2m_sde_gpu" },
    "SDXL/sdXL_v10VAEFix.safetensors": { displayName: "SDXL V10", sampler: "dpmpp_2m_sde_gpu" },
    "SDXL/sdxlPhotorealisticMix_v10.safetensors": { displayName: "SDXLPhotorealisticMix V10", sampler: "dpmpp_2m_sde_gpu" },
    "SDXL/sdxxxl_v30.safetensors": { displayName: "SDXXXL V30", sampler: "dpmpp_2m_sde_gpu" },
    "SDXL/STOIQOAfroditeFLUXXL_XL31.safetensors": { displayName: "STOIQOAfroditeFLUXXL V31", sampler: "dpmpp_2m_sde_gpu" },
    "SDXL/stoiqoNewrealityFLUXSD35_XLPRO.safetensors": { displayName: "StoiqoNewrealityFLUXSD35", sampler: "dpmpp_2m_sde_gpu" },
    "SDXL/unstableIllusion_sdxxxl.safetensors": {
        displayName: "Unstable Illusion SDXXXL (dpmpp_2m/karras, 35, 3.5, CLIP Skip 2)",
        sampler: "dpmpp_2m_sde_gpu",
    },
    "SDXL-Lightning/agxl_LightningV10.safetensors": { displayName: "AGXL Lightning V10", sampler: "lcm" },
    "SDXL-Lightning/babesByStableYogi_v4XLLightning.safetensors": {
        displayName: "BabesByStableYogi V4XL Lightning",
        sampler: "lcm",
    },
    "SDXL-Lightning/copaxTimeless_photorealismSDXL8Step.safetensors": {
        displayName: "CopaxTimeless PhotorealismSDXL",
        sampler: "lcm",
    },
    "SDXL-Lightning/dreamshaperXL_lightningDPMSDE.safetensors": {
        displayName: "DreamshaperXL Lightning",
        sampler: "lcm",
    },
    "SDXL-Lightning/Epicrealismxl_Hades.safetensors": { displayName: "EpicRealismXL Hades", sampler: "lcm" },
    "SDXL-Lightning/epicrealismXL_vxviLastfameDMD2.safetensors": {
        displayName: "epiCRealism XL VXVI LastFAME DMD2 (lcm/normal, 8, 1, CLIP Skip 2)",
        sampler: "lcm",
    },
    "SDXL-Lightning/jibMixRealisticXL_v10Lightning46Step.safetensors": {
        displayName: "JibMixRealisticXL V10 Lightning",
        sampler: "lcm",
    },
    "SDXL-Lightning/juggernautXL_v9Rdphoto2Lightning.safetensors": {
        displayName: "JuggernautXL V9 Lightning",
        sampler: "lcm",
    },
    "SDXL-Lightning/leosamsHelloworldXL_hw50EulerALightning.safetensors": {
        displayName: "HelloworldXL V50 Lightning",
        sampler: "lcm",
    },
    "SDXL-Lightning/lustifySDXLNSFW_endgameDMD2.safetensors": {
        displayName: "Lustify Endgame DMD2 (lcm/normal, 8, 1, CLIP Skip 2)",
        sampler: "lcm",
    },
    "SDXL-Lightning/lustifySDXLNSFW_v40DMD2.safetensors": {
        displayName: "Lustify v4.0 DMD2 (lcm/normal, 8, 1, CLIP Skip 2)",
        sampler: "lcm",
    },
    "SDXL-Lightning/mklanRealistic_mklan220reallight4s.safetensors": {
        displayName: "MklanRealistic Lightning",
        sampler: "lcm",
    },
    "SDXL-Lightning/realismByStableYogi_v5XLLightning.safetensors": {
        displayName: "RealismByStableYogi V5XL Lightning",
        sampler: "lcm",
    },
    "SDXL-Lightning/RealitiesEdgeXLLIGHTNING_LIGHTNING34Step.safetensors": {
        displayName: "RealitiesEdgeXL Lightning",
        sampler: "lcm",
    },
    "SDXL-Lightning/realvisxlV50_v50LightningBakedvae.safetensors": {
        displayName: "RealvisXL V50 Lightning",
        sampler: "lcm",
    },
    "SDXL-Lightning/stoiqoNewrealityFLUXSD35_XLLight10.safetensors": {
        displayName: "StoiqoNewrealityFLUXSD35 Lightning",
        sampler: "lcm",
    },
    "SDXL-Lightning/wildcardxXLLIGHTNING_wildcardxXL.safetensors": {
        displayName: "WildCardX-XL (dpmpp_sde/karras, 6, 1.5, CLIP Skip 2)",
        sampler: "lcm",
    },
};

// Checkpoints
function fetchCheckpointOptions() {
    if (checkpointCache.checkpoints) return checkpointCache.checkpoints;

    // Daftar checkpoint dasar
    const baseCheckpoints = [
        "---- Illustrious ----",
        "Illustrious/cyberillustrious_v30.safetensors",
        "Illustrious/novaRealityXL_illustriousV20.safetensors",
        "Illustrious/perfectionRealisticILXL_v12.safetensors",
        "Illustrious/realismIllustriousBy_v30FP16.safetensors",
        "Illustrious/redcraftCADSUpdatedMar11_illust3relustion.safetensors",
        "Illustrious/rillusmRealistic_v20.safetensors",
        "---- Pony ----",
        "Pony/3xthreat2kModelThatUsesPONY_v10.safetensors",
        "Pony/babesByStableYogi_ponyV4VAEFix.safetensors",
        "Pony/cyberrealisticPony_v85.safetensors",
        "Pony/fasercore_v30PonyFP16.safetensors",
        "Pony/fucktasticRealCheckpointPony_21.safetensors",
        "Pony/iniverseMixSFWNSFW_ponyRealGuofengV50C.safetensors",
        "Pony/ponyDiffusionV6XL.safetensors",
        "Pony/pornyPonyByStable_v20FP16.safetensors",
        "Pony/realDream_sdxlPony15.safetensors",
        "Pony/realismByStableYogi_v40FP16.safetensors",
        "Pony/uberRealisticPornMergePonyxl_ponyxlHybridV1.safetensors",
        "---- SDXL ----",
        "SDXL/acornIsBoningXL_xlV2.safetensors",
        "SDXL/agxl_V2.safetensors",
        "SDXL/animaPencilXL_v500.safetensors",
        "SDXL/annolustxl_v2.safetensors",
        "SDXL/babesByStableYogi_v4XLFP16.safetensors",
        "SDXL/bestPornMergeBPM_v10.safetensors",
        "SDXL/biglovexl2.wBWt.safetensors",
        "SDXL/biglust16.kst6.safetensors",
        "SDXL/boomerArtModelBAM_bamV2.safetensors",
        "SDXL/clarityXL_v20.safetensors",
        "SDXL/cyberprimeXL_v10.safetensors",
        "SDXL/cyberrealisticXL_v5.safetensors",
        "SDXL/d33psixSDXL_d33psixSDXL.safetensors",
        "SDXL/epicrealismXL_vxvAnewstoryRealism.safetensors",
        "SDXL/epicrealismXL_vxviLastfameRealism.safetensors",
        "SDXL/fasercore_xlV1.safetensors",
        "SDXL/jibMixRealisticXL_v160Aphrodite.safetensors",
        "SDXL/juggernautXL_juggXIByRundiffusion.safetensors",
        "SDXL/leosamsHelloworldXL_helloworldXL70.safetensors",
        "SDXL/lustifySDXLNSFW_endgame.safetensors",
        "SDXL/lustifySDXLNSFW_oltONELASTTIME.safetensors",
        "SDXL/lustimix_.safetensors",
        "SDXL/lustimix_big.safetensors",
        "SDXL/lustimix_bigRebirth.safetensors",
        "SDXL/mumixxl_v11.safetensors",
        "SDXL/msSDXLRealV3_v3.safetensors",
        "SDXL/novaRealityXL_v70.safetensors",
        "SDXL/omnigenxlNSFWSFW_v10.safetensors",
        "SDXL/perfectionRealisticILXL_v10.safetensors",
        "SDXL/photoart_V40.safetensors",
        "SDXL/photopediaXL_45.safetensors",
        "SDXL/polyhedronSDXL_v3.safetensors",
        "SDXL/pornmaster_proSDXLV3VAE.safetensors",
        "SDXL/realismByStableYogi_v5XLFP16.safetensors",
        "SDXL/realismEngineSDXL_v30VAE.safetensors",
        "SDXL/realisticLustXL_v05.safetensors",
        "SDXL/realisticStockPhoto_v20.safetensors",
        "SDXL/realvisxlV50_v50Bakedvae.safetensors",
        "SDXL/sd_xl_base_1.0_0.9vae.safetensors",
        "SDXL/sd_xl_refiner_1.0.safetensors",
        "SDXL/sdXL_v10VAEFix.safetensors",
        "SDXL/sdxlPhotorealisticMix_v10.safetensors",
        "SDXL/sdxxxl_v30.safetensors",
        "SDXL/STOIQOAfroditeFLUXXL_XL31.safetensors",
        "SDXL/stoiqoNewrealityFLUXSD35_XLPRO.safetensors",
        "SDXL/unstableIllusion_sdxxxl.safetensors",
        "---- SDXL Lightning ----",
        "SDXL-Lightning/agxl_LightningV10.safetensors",
        "SDXL-Lightning/babesByStableYogi_v4XLLightning.safetensors",
        "SDXL-Lightning/copaxTimeless_photorealismSDXL8Step.safetensors",
        "SDXL-Lightning/dreamshaperXL_lightningDPMSDE.safetensors",
        "SDXL-Lightning/Epicrealismxl_Hades.safetensors",
        "SDXL-Lightning/epicrealismXL_vxviLastfameDMD2.safetensors",
        "SDXL-Lightning/jibMixRealisticXL_v10Lightning46Step.safetensors",
        "SDXL-Lightning/juggernautXL_v9Rdphoto2Lightning.safetensors",
        "SDXL-Lightning/leosamsHelloworldXL_hw50EulerALightning.safetensors",
        "SDXL-Lightning/lustifySDXLNSFW_endgameDMD2.safetensors",
        "SDXL-Lightning/lustifySDXLNSFW_v40DMD2.safetensors",
        "SDXL-Lightning/mklanRealistic_mklan220reallight4s.safetensors",
        "SDXL-Lightning/realismByStableYogi_v5XLLightning.safetensors",
        "SDXL-Lightning/RealitiesEdgeXLLIGHTNING_LIGHTNING34Step.safetensors",
        "SDXL-Lightning/realvisxlV50_v50LightningBakedvae.safetensors",
        "SDXL-Lightning/stoiqoNewrealityFLUXSD35_XLLight10.safetensors",
        "SDXL-Lightning/wildcardxXLLIGHTNING_wildcardxXL.safetensors",
    ];

    checkpointCache.checkpoints = baseCheckpoints.map((ckpt) => ckpt);
    return checkpointCache.checkpoints;
}

// Samplers
function fetchSamplerOptions() {
    return [
        "euler",
        "euler_cfg_pp",
        "euler_ancestral",
        "euler_ancestral_cfg_pp",
        "heun",
        "heunpp2",
        "dpm_2",
        "dpm_2_ancestral",
        "lms",
        "dpm_fast",
        "dpm_adaptive",
        "dpmpp_2s_ancestral",
        "dpmpp_2s_ancestral_cfg_pp",
        "dpmpp_sde",
        "dpmpp_sde_gpu",
        "dpmpp_2m",
        "dpmpp_2m_cfg_pp",
        "dpmpp_2m_sde",
        "dpmpp_2m_sde_gpu",
        "dpmpp_3m_sde",
        "dpmpp_3m_sde_gpu",
        "ddpm",
        "lcm",
        "ipndm",
        "ipndm_v",
        "deis",
        "res_multistep",
        "res_multistep_cfg_pp",
        "res_multistep_ancestral",
        "res_multistep_ancestral_cfg_pp",
        "gradient_estimation",
        "er_sde",
    ];
}

// Schedulers
function fetchSchedulerOptions() {
    return [
        "normal",
        "karras",
        "exponential",
        "sgm_uniform",
        "simple",
        "ddim_uniform",
        "beta",
        "linear_quadratic",
        "kl_optimal",
    ];
}
