const NSFWPresets = {
    none: { label: "Tidak Ada", prompts: {} },
    "cum on face": {
        label: "Cum on Face",
        prompts: {
            1: "raw 8K night portrait, 30-year-old British woman, nude on bed, medium breasts with visible nipples and areolas, freckles, eyeliner, face covered in cum from one man, cum trails on wet face, hair, and body, tongue out, direct eye contact, flash photography, dark setting, amateur vibe, high detail, wet messy aesthetic",
            2: "photorealistic 4K, 25-year-old woman, long blonde hair, pale skin, small breasts, kneeling on floor, cum on face from one man, glossy lips, soft bedroom lighting, high detail, intimate atmosphere",
            3: "cinematic 8K, 32-year-old woman, short black hair, tan skin, medium breasts, sitting on couch, cum on face from one man, drooling slightly, warm living room light, realistic textures, seductive gaze",
            4: "amateur-style photo, 20-year-old woman, curly red hair, freckles, large breasts, lying on bed, cum on face from one man, messy hair, natural daylight, casual vibe, sharp focus",
            5: "hyperrealistic, 28-year-old woman, wavy brown hair, medium breasts, standing in bathroom, cum on face from one man, wet skin, steamy mirror background, soft lighting, detailed pores",
            6: "RAW 4K photo, 35-year-old woman, long dark hair, curvy figure, small breasts, sitting at desk, cum on face from one man, office setting, warm lamp glow, realistic shadows",
            7: "cinematic NSFW, 22-year-old woman, platinum blonde ponytail, fair skin, medium breasts, kneeling outdoors, cum on face from one man, sunset lighting, grassy field, high detail, sensual expression",
            8: "photorealistic 8K, 27-year-old woman, short bob haircut, tan skin, large breasts, lying on beach towel, cum on face from one man, ocean waves in background, bright sunlight, wet hair",
            9: "high-quality photo, 29-year-old woman, long chestnut hair, slim build, small breasts, sitting in car, cum on face from one man, night streetlights, foggy windows, intimate vibe",
            10: "ultra-sharp 4K, 31-year-old woman, black hair in bun, pale skin, medium breasts, standing in kitchen, cum on face from one man, morning light, apron only, realistic textures",
        },
    },
    "cumshot on tongue": {
        label: "Cumshot on Tongue",
        prompts: {
            1: "beautiful 30-year-old blonde woman, heavy makeup, blue eyes, cum on face from one man, tongue out with thick white cum, detailed face, visible skin pores, high-angle shot, photorealistic, sharp focus",
            2: "cinematic 4K, 24-year-old woman, long brown hair, green eyes, tongue out with cum from one man, medium breasts, kneeling in bedroom, soft lighting, realistic skin, intimate POV",
            3: "RAW photo, 28-year-old woman, short black hair, fair skin, tongue out with cum from one man, small breasts, sitting on floor, dim living room, warm glow, high detail",
            4: "photorealistic 8K, 21-year-old woman, curly blonde hair, tan skin, tongue out with cum from one man, large breasts, lying on couch, natural daylight, seductive look, sharp textures",
            5: "amateur-style, 33-year-old woman, wavy red hair, freckles, tongue out with cum from one man, medium breasts, kneeling in bathroom, wet hair, soft lighting, casual vibe",
            6: "high-quality 4K, 26-year-old woman, long dark hair, pale skin, tongue out with cum from one man, small breasts, sitting outdoors, sunset glow, grassy background, realistic detail",
            7: "cinematic NSFW, 29-year-old woman, short bob haircut, brown eyes, tongue out with cum from one man, medium breasts, standing in shower, water droplets, steamy atmosphere, sharp focus",
            8: "hyperrealistic, 23-year-old woman, platinum blonde, blue eyes, tongue out with cum from one man, large breasts, lying on bed, warm bedroom light, wet lips, high detail",
            9: "RAW 8K, 31-year-old woman, long chestnut hair, tan skin, tongue out with cum from one man, small breasts, sitting in car, night lighting, intimate setting, realistic pores",
            10: "photorealistic, 27-year-old woman, curly black hair, medium breasts, tongue out with cum from one man, kneeling on balcony, city skyline at dusk, soft glow, ultra-sharp",
        },
    },
    dildo: {
        label: "Dildo",
        prompts: {
            1: "seductive atmosphere, confident woman, medium bouncing breasts, enlarged nipples, using fully inserted dildo vaginally, legs spread wide, dynamic low-angle shot, passionate intensity, realistic textures, soft lighting",
            2: "photorealistic 8K, 25-year-old woman, long blonde hair, pale skin, small breasts, using dildo vaginally, sitting on bed, legs apart, warm bedroom light, high detail, sensual pose",
            3: "cinematic 4K, 30-year-old woman, wavy brown hair, tan skin, large breasts, using dildo vaginally, lying on couch, legs spread, soft living room glow, realistic skin, intimate vibe",
            4: "amateur-style photo, 22-year-old woman, short black hair, freckles, medium breasts, using dildo vaginally, kneeling on floor, natural daylight, casual setting, sharp focus",
            5: "hyperrealistic, 28-year-old woman, curly red hair, fair skin, small breasts, using dildo vaginally, standing in shower, wet skin, steamy background, soft lighting, high detail",
            6: "RAW 4K, 33-year-old woman, long dark hair, curvy figure, large breasts, using dildo vaginally, lying on rug, legs apart, warm fireplace light, realistic textures, seductive gaze",
            7: "cinematic NSFW, 26-year-old woman, platinum blonde ponytail, medium breasts, using dildo vaginally, sitting on chair, legs spread, dim kitchen light, high detail, intimate atmosphere",
            8: "photorealistic 8K, 29-year-old woman, short bob haircut, tan skin, small breasts, using dildo vaginally, lying on beach towel, legs apart, ocean waves, bright sunlight, sharp textures",
            9: "high-quality photo, 24-year-old woman, long chestnut hair, pale skin, medium breasts, using dildo vaginally, kneeling on balcony, city skyline at night, soft glow, realistic detail",
            10: "ultra-sharp 4K, 31-year-old woman, curly black hair, large breasts, using dildo vaginally, sitting in bathtub, bubbly water, candlelight, legs spread, sensual pose, high detail",
        },
    },
    "from behind": {
        label: "From Behind",
        prompts: {
            1: "photorealistic, woman in dimly lit room, 30-year-old, slim body, lying on stomach, light brown long-sleeved top, short blue skirt pulled up, revealing ass and pussy, long brown hair, centered composition, dim lighting, shadows, uncensored, detailed skin, no panties, pussy juice, all fours, close-up vagina view",
            2: "18-year-old Goth e-girl, blonde ponytail, fair skin, petite frame, small saggy breasts, erect nipples, bubble butt, blemishes, freckles, arm tattoo, winged eyeliner, eye contact, rear-view, spreading ass, realistic webcam style, film grain, soft dynamic lighting, dark blurred background",
            3: "photorealistic 8K, topless brunette, long braided hair, shiny skin, black tights, close-up of round big butt, dynamic motion shot, dramatic angle, soft diffused lighting, vagina in focus, dark moody background, cinematic, rich colors, sharp details, mystical romantic vibe",
            4: "anime-style masterpiece, ultra-high resolution, 30-year-old blonde, long straight hair, blue eyes, black eyeshadow, pale skin, athletic body, huge hips, thick thighs, round ass, perfect breasts, hard nipples, oiled shiny skin, all fours, ass up, spreading ass, revealing pussy, horny expression, sharp contours, bright colors, blurred castle background, uncensored",
            5: "amateur voyeur photo, luxury apartment lounge, daytime, candid nudity, 30-year-old brunette, messy long hair, white crop top, fingering pussy, visible ass, shaved pubic hair, film grain, JPEG quality, casual distracted vibe",
            6: "busty secretary, leaning over desk, spreading butt, wet pussy with dripping creampie from one man, photorealistic, high detail, warm lighting, office setting",
            7: "masterpiece side-profile, 22-year-old Latina supermodel, tan skin, freckles, medium saggy breasts, tiny puffy nipples, open shirt, low panties, pajama bottoms, lying on bed, spreading ass cheeks, dripping creampie from one man, sensual expression, photorealistic, soft indoor lighting",
            8: "amateur raw photo, dim bedroom, warm night lamp, cute blonde, lying on stomach, black shirt, perfect ass, thick thighs, creampie from one man, cum dripping from pussy, realistic textures, casual vibe",
            9: "cinematic 4K, 27-year-old woman, long wavy red hair, pale skin, medium breasts, kneeling on rug, ass up, pussy visible, warm fireplace glow, realistic shadows, high detail, intimate setting",
            10: "photorealistic 8K, 24-year-old woman, short black hair, tan skin, small breasts, lying on beach towel, ass raised, pussy visible, ocean waves in background, bright sunlight, sharp textures",
        },
    },
    "kneeling blowjob": {
        label: "Kneeling Blowjob",
        prompts: {
            1: "30-year-old woman, blonde ponytail, fair skin, medium breasts, bubble butt, blemishes, freckles, kneeling in dimly lit bedroom, messy deepthroat blowjob on one man, drool dripping, realistic webcam style, film grain, soft dynamic lighting, NSFW",
            2: "photorealistic NSFW, 19-year-old woman, messy wet hair, glistening skin, blowjob on one man’s large penis, top-down POV, intense gaze, athletic pose, rain setting, saliva dripping, ripped Supergirl cosplay, ominous jungle, Nikon F4, 50mm f1.2, Fujichrome Velvia 50, bokeh, edgy rock vibe",
            3: "side-view blowjob, beautiful woman, one standing man, perfect lighting, small breasts, deepthroat, creampie, tan lines, photorealistic, high detail, cinematic composition",
            4: "realistic, cinematic, 8K RAW photo, woman kneeling, blowjob on one man, deepthroat, cum on face, runny makeup, hand on head, wet penis, soft lighting, film grain, Fujifilm XT3, high-quality textures, POV",
            5: "photorealistic NSFW, 30-year-old Japanese MILF, messy black wet hair, licking one man’s large veiny black penis, side POV, freckles, acne, wrinkles, detailed skin, dark basement, flash photography, cum on tongue and face, amateur interracial style",
            6: "blowjob, fellatio, young beautiful woman, oiled skin, light reflections, performing on one man, high detail, realistic textures, soft lighting",
            7: "medium-quality ultrasharp photo, long-haired brunette, brown eyes, kneeling, fellatio on one man’s uncensored penis, cum in mouth and on face, freckles, POV from above, realistic, high detail, aesthetic erotic style",
            8: "high-quality explicit photo, 21-year-old Danish girl, curvy slim figure, wavy chestnut hair, sleepy sad expression, kneeling nude, deep blowjob on one man, excessive cum on face and hair, hair grab by one man, side-view, natural daylight, low contrast, gritty lomography, cozy messy bedroom",
            9: "cinematic 4K, 25-year-old woman, short blonde hair, tan skin, medium breasts, kneeling on beach, blowjob on one man, wet hair, ocean waves, sunset lighting, realistic textures, intimate POV",
            10: "RAW 8K photo, 28-year-old woman, long curly red hair, pale skin, small breasts, kneeling in shower, blowjob on one man, water dripping, steamy atmosphere, soft lighting, high detail",
        },
    },
    "kneeling tongue out": {
        label: "Kneeling Tongue Out",
        prompts: {
            1: "beautiful 35-year-old woman, kneeling, eyes closed, long hair, tongue out, anticipation, POV, realistic teeth, detailed skin, goosebumps, cinematic bedroom, photorealistic, fisheye lens, black casual outfit with bra and panties, medium breasts, natural white light",
            2: "photorealistic 8K, 23-year-old woman, short black hair, tan skin, small breasts, kneeling on floor, tongue out, seductive gaze, dim living room, warm lamp glow, high detail, intimate vibe",
            3: "cinematic 4K, 29-year-old woman, long blonde hair, pale skin, medium breasts, kneeling in bathroom, tongue out, wet hair, steamy mirror background, soft lighting, realistic textures",
            4: "amateur-style photo, 21-year-old woman, curly red hair, freckles, large breasts, kneeling on bed, tongue out, natural daylight, casual setting, sharp focus, sensual pose",
            5: "hyperrealistic, 27-year-old woman, wavy brown hair, fair skin, small breasts, kneeling outdoors, tongue out, sunset glow, grassy field, high detail, expressive look",
            6: "RAW 4K, 32-year-old woman, long dark hair, curvy figure, medium breasts, kneeling in kitchen, tongue out, morning light, apron only, realistic shadows, intimate atmosphere",
            7: "cinematic NSFW, 25-year-old woman, platinum blonde ponytail, tan skin, large breasts, kneeling on balcony, tongue out, city skyline at dusk, soft glow, high detail",
            8: "photorealistic 8K, 30-year-old woman, short bob haircut, pale skin, small breasts, kneeling on beach, tongue out, ocean waves, bright sunlight, wet hair, sharp textures",
            9: "high-quality photo, 26-year-old woman, long chestnut hair, medium breasts, kneeling in car, tongue out, night streetlights, foggy windows, intimate vibe, realistic detail",
            10: "ultra-sharp 4K, 28-year-old woman, curly black hair, large breasts, kneeling in shower, tongue out, water droplets, steamy atmosphere, soft lighting, high detail",
        },
    },
    penetration: {
        label: "Penetration",
        prompts: {
            1: "cinematic 4K, gorgeous thicc woman, freckles, sexy figure, squatting cowgirl position on one man, vaginal penetration, close-up POV below, motion blur, moaning, uncensored, puffy nipples, sharp focus, moody vignette, grainy detail",
            2: "photorealistic 8K, 25-year-old woman, long blonde hair, pale skin, medium breasts, missionary position with one man, vaginal penetration, lying on bed, warm bedroom light, realistic sweat, high detail",
            3: "RAW 4K photo, 30-year-old woman, short black hair, tan skin, small breasts, doggy-style with one man, vaginal penetration, on floor, dim living room, soft glow, realistic textures",
            4: "cinematic NSFW, 22-year-old woman, curly red hair, fair skin, large breasts, reverse cowgirl on one man, vaginal penetration, sitting on couch, natural daylight, dynamic angle, sharp focus",
            5: "hyperrealistic, 28-year-old woman, wavy brown hair, medium breasts, standing sex with one man, vaginal penetration, against wall, wet skin, steamy bathroom, soft lighting, high detail",
            6: "amateur-style photo, 33-year-old woman, long dark hair, curvy figure, small breasts, missionary with one man, vaginal penetration, on rug, warm fireplace light, realistic shadows, intimate vibe",
            7: "photorealistic 8K, 26-year-old woman, platinum blonde ponytail, tan skin, medium breasts, cowgirl on one man, vaginal penetration, on chair, dim kitchen light, high detail, sensual motion",
            8: "high-quality 4K, 29-year-old woman, short bob haircut, pale skin, large breasts, doggy-style with one man, vaginal penetration, on beach towel, ocean waves, sunset lighting, sharp textures",
            9: "cinematic 4K, 24-year-old woman, long chestnut hair, fair skin, small breasts, standing sex with one man, vaginal penetration, on balcony, city skyline at night, soft glow, realistic detail",
            10: "RAW 8K, 31-year-old woman, curly black hair, large breasts, missionary with one man, vaginal penetration, in bathtub, bubbly water, candlelight, high detail, intimate atmosphere",
        },
    },
    "pov blowjob": {
        label: "POV Blowjob",
        prompts: {
            1: "cinematic 4K, 30-year-old Korean woman, long dark hair, delicate features, POV blowjob on one man, detailed lips, saliva, cum on face and dripping, professional bokeh, high detail, realistic textures",
            2: "high-quality 8K cinematic, 30-year-old woman, POV blowjob on one man, cum on face, medium breasts, visible nipples, exposed pussy, shot from above, sharp focus, realistic lighting",
            3: "photorealistic 35mm film, 30-year-old Korean woman, long wet hair, deepthroating one man’s cock, drool and cum dripping, small tits, lingerie and nude, passionate expression, cinematic bokeh, film grain, ultra-sharp",
            4: "RAW 4K photo, 25-year-old woman, short blonde hair, tan skin, POV blowjob on one man, wet lips, cum on face, medium breasts, kneeling on floor, dim bedroom light, realistic textures",
            5: "cinematic NSFW, 22-year-old woman, curly red hair, pale skin, POV blowjob on one man, saliva dripping, large breasts, sitting on couch, natural daylight, high detail, intimate vibe",
            6: "hyperrealistic, 28-year-old woman, wavy brown hair, fair skin, POV blowjob on one man, cum on tongue, small breasts, kneeling outdoors, sunset glow, grassy field, sharp focus",
            7: "amateur-style 8K, 33-year-old woman, long dark hair, curvy figure, POV blowjob on one man, drool on chin, medium breasts, in bathroom, wet hair, soft lighting, realistic detail",
            8: "photorealistic 4K, 26-year-old woman, platinum blonde ponytail, tan skin, POV blowjob on one man, cum on face, large breasts, kneeling on beach, ocean waves, bright sunlight, high detail",
            9: "high-quality photo, 29-year-old woman, short bob haircut, pale skin, POV blowjob on one man, wet penis, small breasts, in car, night streetlights, foggy windows, sharp textures",
            10: "ultra-sharp 8K, 31-year-old woman, curly black hair, medium breasts, POV blowjob on one man, cum dripping, kneeling on balcony, city skyline at dusk, soft glow, realistic pores",
        },
    },
    "spreading legs": {
        label: "Spreading Legs",
        prompts: {
            1: "solo woman, long brown hair, large breasts, brown eyes, nude, lying on back, legs spread, pussy visible, indoors, night, wet pussy, detailed skin, uncensored, cinematic bedroom, moonlit background",
            2: "solo woman, long blonde hair, blue eyes, medium breasts, short-sleeve blue shirt, bottomless, lying on back, legs spread, masturbating, realistic, uncensored, bedroom, close-up shot",
            3: "seductive brunette, yellow taxi backseat, New York, flashing medium breasts and pubic hair, provocative pose, soft-focus lens, cinematic haze, glossy lips, smoldering gaze",
            4: "skinny curvy woman, medium breasts, pink nipples, black hair, ripped sheer tights, wet pussy, bondage with leather straps, shy orgasmic expression, Dutch angle, cold soft lighting, comic book style, disco club, shiny skin",
            5: "gorgeous young woman, transparent nightgown, lifting gown, revealing pussy and ass, POV angle, seductive blush, expressive gaze, photorealistic, soft lighting",
            6: "seductive woman, wavy light brown hair, huge natural breasts, light red nipples, shaved pussy spread, nude, night, flash photography, chiaroscuro lighting, high contrast, detailed face, 4K NSFW",
            7: "30-year-old woman, wavy light brown hair, black lingerie, garter belt, huge natural breasts, shaved pussy spread with cum dripping from one man, elegant heels, night, flash photography, chiaroscuro, 4K NSFW",
            8: "sexy 30-year-old blonde, short streaked hair, red dress, black thigh-high stockings, splayed thighs, hairy pussy, upskirt view, sharp focus, raunchy pose, perfect figure, high-quality photo",
            9: "hyperrealistic, skinny goth girl, black hair with red highlights, green eyes, huge saggy breasts, fishnet stockings, squatting or lying back, spreading pussy, detailed labia, sweaty steamy look, soft lighting, vivid textures",
            10: "cinematic 4K, goth girl, black hair with blue highlights, red eyes, lying back, legs spread, fingering pussy, perky saggy breasts, dark nipples, pubic stubble, moody vignette, soft lighting, Kodak 35mm, emotional romantic vibe",
            11: "nude woman, long brown hair, lying on bed, legs spread, wet pussy with semen dripping from one man, satisfied expression, harsh flash photography, realistic textures, high detail",
        },
    },
    "shower tease": {
        label: "Shower Tease",
        prompts: {
            1: "photorealistic 8K, 25-year-old woman, wet black hair, medium breasts with erect nipples, glistening skin, standing in steamy shower, legs slightly apart, water droplets on body, seductive gaze, soft lighting, high detail, misty background",
            2: "cinematic 4K, 30-year-old woman, long blonde hair, pale skin, small breasts, standing in shower, legs apart, wet skin, soap suds, warm lighting, realistic textures, sensual pose",
            3: "RAW photo, 22-year-old woman, curly red hair, tan skin, large breasts, sitting in shower, legs spread, water streaming, steamy atmosphere, soft glow, high detail",
            4: "hyperrealistic, 28-year-old woman, short bob haircut, fair skin, medium breasts, leaning against shower wall, legs apart, wet hair, misty background, soft lighting, sharp focus",
            5: "amateur-style 8K, 33-year-old woman, wavy brown hair, curvy figure, small breasts, standing in shower, legs slightly apart, water droplets, natural light, casual vibe, realistic detail",
            6: "cinematic NSFW, 26-year-old woman, platinum blonde ponytail, tan skin, large breasts, sitting on shower floor, legs spread, wet skin, steamy air, warm glow, high detail",
            7: "photorealistic 4K, 29-year-old woman, long dark hair, pale skin, medium breasts, standing in shower, legs apart, soap on body, misty background, soft lighting, seductive look",
            8: "high-quality photo, 24-year-old woman, short black hair, fair skin, small breasts, leaning forward in shower, legs spread, water dripping, steamy atmosphere, sharp textures",
            9: "ultra-sharp 8K, 31-year-old woman, curly chestnut hair, tan skin, large breasts, standing in shower, legs apart, wet skin, soft lighting, misty backdrop, high detail",
            10: "RAW 4K, 27-year-old woman, long red hair, pale skin, medium breasts, sitting in shower, legs spread, water flowing, steamy environment, warm light, realistic pores",
        },
    },
    "missionary passion": {
        label: "Missionary Passion",
        prompts: {
            1: "cinematic 4K, 28-year-old woman, long red hair, pale skin, large breasts, lying on back on silk sheets, legs spread, vaginal sex with one man, intense expression, sweat on skin, warm bedroom lighting, shallow depth of field, realistic textures",
            2: "photorealistic 8K, 25-year-old woman, blonde hair, tan skin, medium breasts, lying on bed, vaginal sex with one man, legs spread, moaning, soft lighting, high detail, intimate vibe",
            3: "RAW photo, 30-year-old woman, short black hair, fair skin, small breasts, lying on rug, vaginal sex with one man, legs apart, warm fireplace glow, realistic sweat, sharp focus",
            4: "hyperrealistic, 22-year-old woman, wavy brown hair, pale skin, large breasts, lying on couch, vaginal sex with one man, legs spread, natural daylight, sensual expression, high detail",
            5: "cinematic NSFW, 33-year-old woman, long dark hair, curvy figure, medium breasts, lying on floor, vaginal sex with one man, legs apart, dim living room, soft glow, realistic textures",
            6: "amateur-style 8K, 26-year-old woman, platinum blonde ponytail, tan skin, small breasts, lying on bed, vaginal sex with one man, legs spread, morning light, casual vibe, sharp focus",
            7: "photorealistic 4K, 29-year-old woman, short bob haircut, fair skin, large breasts, lying on beach towel, vaginal sex with one man, legs apart, ocean waves, sunset lighting, high detail",
            8: "high-quality photo, 24-year-old woman, curly red hair, pale skin, medium breasts, lying on balcony, vaginal sex with one man, legs spread, city skyline at dusk, soft glow, realistic detail",
            9: "ultra-sharp 8K, 31-year-old woman, long chestnut hair, tan skin, small breasts, lying in bathtub, vaginal sex with one man, legs apart, bubbly water, candlelight, high detail",
            10: "RAW 4K, 27-year-old woman, curly black hair, fair skin, large breasts, lying on kitchen counter, vaginal sex with one man, legs spread, morning light, realistic textures",
        },
    },
    "topless beach": {
        label: "Topless Beach",
        prompts: {
            1: "hyperrealistic, 22-year-old woman, blonde bob haircut, tan skin, small perky breasts, standing on sandy beach, ocean waves in background, sunglasses on head, wet hair, subtle smile, bright sunlight, detailed skin pores, uncensored",
            2: "photorealistic 8K, 28-year-old woman, long dark hair, pale skin, medium breasts, walking on beach, waves crashing, wet skin, soft breeze, sunny day, high detail, natural pose",
            3: "cinematic 4K, 25-year-old woman, wavy brown hair, tan skin, large breasts, lying on beach towel, ocean in background, sunglasses, glistening skin, bright sunlight, realistic textures",
            4: "RAW photo, 30-year-old woman, short black hair, fair skin, small breasts, standing in shallow water, waves around legs, wet hair, sunny afternoon, sharp focus, detailed pores",
            5: "amateur-style 8K, 33-year-old woman, curly red hair, pale skin, medium breasts, sitting on sand, ocean horizon, natural light, casual vibe, high detail, subtle tan lines",
            6: "cinematic NSFW, 26-year-old woman, platinum blonde ponytail, tan skin, large breasts, kneeling on beach, waves in distance, wet skin, sunset glow, realistic shadows, sharp textures",
            7: "photorealistic 4K, 29-year-old woman, long chestnut hair, fair skin, small breasts, standing on rocky shore, ocean spray, bright sunlight, natural pose, high detail",
            8: "high-quality photo, 24-year-old woman, short bob haircut, tan skin, medium breasts, lying on beach chair, waves nearby, sunglasses on head, sunny day, realistic skin, sharp focus",
            9: "ultra-sharp 8K, 31-year-old woman, curly black hair, pale skin, large breasts, walking along shoreline, ocean waves, wet hair, soft breeze, bright sunlight, high detail",
            10: "RAW 4K, 27-year-old woman, long red hair, tan skin, small breasts, sitting on beach towel, waves in background, natural light, subtle smile, realistic textures",
        },
    },
    "kitchen seduction": {
        label: "Kitchen Seduction",
        prompts: {
            1: "amateur-style photo, 35-year-old woman, brunette with messy bun, medium breasts, wearing only apron, leaning against kitchen counter, legs apart, pussy visible, warm morning light, candid vibe, realistic shadows, high detail",
            2: "photorealistic 8K, 25-year-old woman, long blonde hair, tan skin, small breasts, standing in kitchen, apron only, legs spread, pussy visible, soft sunlight, high detail, seductive pose",
            3: "cinematic 4K, 30-year-old woman, wavy brown hair, pale skin, large breasts, sitting on kitchen counter, apron lifted, pussy visible, warm lighting, realistic textures, intimate vibe",
            4: "RAW photo, 22-year-old woman, short black hair, fair skin, medium breasts, leaning over kitchen table, apron only, legs apart, pussy visible, natural daylight, sharp focus",
            5: "hyperrealistic, 28-year-old woman, curly red hair, tan skin, small breasts, standing by stove, apron only, legs spread, pussy visible, warm glow, high detail, sensual look",
            6: "cinematic NSFW, 33-year-old woman, long dark hair, curvy figure, large breasts, sitting on kitchen floor, apron lifted, pussy visible, soft morning light, realistic shadows",
            7: "photorealistic 4K, 26-year-old woman, platinum blonde ponytail, pale skin, medium breasts, leaning against fridge, apron only, legs apart, pussy visible, natural light, high detail",
            8: "high-quality photo, 29-year-old woman, short bob haircut, tan skin, small breasts, standing by sink, apron only, legs spread, pussy visible, warm sunlight, sharp textures",
            9: "ultra-sharp 8K, 31-year-old woman, curly chestnut hair, fair skin, large breasts, sitting on counter, apron lifted, pussy visible, morning light, realistic pores",
            10: "RAW 4K, 27-year-old woman, long red hair, pale skin, medium breasts, leaning over island, apron only, legs apart, pussy visible, soft glow, high detail",
        },
    },
    "reverse cowgirl": {
        label: "Reverse Cowgirl",
        prompts: {
            1: "photorealistic NSFW, 27-year-old woman, curly black hair, athletic build, medium breasts, riding one man in reverse cowgirl position, facing away, pussy penetration, dim bedroom, soft glow from bedside lamp, dynamic angle, wet skin",
            2: "cinematic 4K, 25-year-old woman, long blonde hair, tan skin, small breasts, reverse cowgirl on one man, vaginal penetration, on bed, warm lighting, realistic sweat, high detail",
            3: "RAW photo, 30-year-old woman, short black hair, pale skin, large breasts, reverse cowgirl on one man, vaginal penetration, on couch, dim living room, soft glow, sharp focus",
            4: "hyperrealistic, 22-year-old woman, wavy brown hair, fair skin, medium breasts, reverse cowgirl on one man, vaginal penetration, on floor, natural daylight, dynamic pose, high detail",
            5: "cinematic NSFW, 33-year-old woman, long dark hair, curvy figure, small breasts, reverse cowgirl on one man, vaginal penetration, on rug, warm fireplace light, realistic textures",
            6: "amateur-style 8K, 26-year-old woman, platinum blonde ponytail, tan skin, large breasts, reverse cowgirl on one man, vaginal penetration, on chair, dim kitchen light, sharp focus",
            7: "photorealistic 4K, 29-year-old woman, short bob haircut, pale skin, medium breasts, reverse cowgirl on one man, vaginal penetration, on beach towel, ocean waves, sunset lighting, high detail",
            8: "high-quality photo, 24-year-old woman, curly red hair, fair skin, small breasts, reverse cowgirl on one man, vaginal penetration, on balcony, city skyline at dusk, soft glow, realistic detail",
            9: "ultra-sharp 8K, 31-year-old woman, long chestnut hair, tan skin, large breasts, reverse cowgirl on one man, vaginal penetration, in bathtub, bubbly water, candlelight, high detail",
            10: "RAW 4K, 28-year-old woman, curly black hair, pale skin, medium breasts, reverse cowgirl on one man, vaginal penetration, on kitchen counter, morning light, realistic textures",
        },
    },
    "bathtub solo": {
        label: "Bathtub Solo",
        prompts: {
            1: "cinematic 8K, 30-year-old woman, long platinum hair, huge natural breasts, sitting in bubbly bathtub, legs spread, fingering pussy, steamy atmosphere, candlelight, reflective water, seductive pose, ultra-sharp details",
            2: "photorealistic 4K, 25-year-old woman, wavy brown hair, tan skin, medium breasts, lying in bathtub, legs apart, masturbating, warm water, soft lighting, realistic textures, intimate vibe",
            3: "RAW photo, 28-year-old woman, short black hair, pale skin, small breasts, sitting in bathtub, legs spread, fingering pussy, bubbly water, dim glow, high detail",
            4: "hyperrealistic, 22-year-old woman, curly red hair, fair skin, large breasts, leaning back in bathtub, legs apart, masturbating, steamy air, candlelight, sharp focus",
            5: "cinematic NSFW, 33-year-old woman, long dark hair, curvy figure, medium breasts, sitting in bathtub, legs spread, fingering pussy, warm water, soft lighting, realistic shadows",
            6: "amateur-style 8K, 26-year-old woman, platinum blonde ponytail, tan skin, small breasts, lying in bathtub, legs apart, masturbating, bubbly water, natural light, high detail",
            7: "photorealistic 4K, 29-year-old woman, short bob haircut, pale skin, large breasts, sitting in bathtub, legs spread, fingering pussy, steamy atmosphere, warm glow, realistic textures",
            8: "high-quality photo, 24-year-old woman, long chestnut hair, fair skin, medium breasts, leaning back in bathtub, legs apart, masturbating, candlelight, sharp focus",
            9: "ultra-sharp 8K, 31-year-old woman, curly black hair, tan skin, small breasts, sitting in bathtub, legs spread, fingering pussy, bubbly water, soft lighting, high detail",
            10: "RAW 4K, 27-year-old woman, long red hair, pale skin, large breasts, lying in bathtub, legs apart, masturbating, steamy air, warm glow, realistic pores",
        },
    },
    "standing quickie": {
        label: "Standing Quickie",
        prompts: {
            1: "raw 4K photo, 24-year-old woman, short brown hair, slim figure, small breasts, standing against wall, vaginal sex with one man, skirt lifted, panties pulled aside, dimly lit hallway, urgent expression, film grain, realistic textures",
            2: "photorealistic 8K, 30-year-old woman, long blonde hair, tan skin, medium breasts, standing in bathroom, vaginal sex with one man, dress lifted, wet skin, steamy mirror, soft lighting, high detail",
            3: "cinematic 4K, 25-year-old woman, wavy brown hair, pale skin, large breasts, standing in kitchen, vaginal sex with one man, apron lifted, morning light, realistic sweat, sharp focus",
            4: "hyperrealistic, 28-year-old woman, short black hair, fair skin, small breasts, standing in closet, vaginal sex with one man, skirt pulled up, dim light, intimate vibe, high detail",
            5: "cinematic NSFW, 33-year-old woman, long dark hair, curvy figure, medium breasts, standing in hallway, vaginal sex with one man, pants down, soft glow, realistic textures",
            6: "amateur-style 8K, 26-year-old woman, platinum blonde ponytail, tan skin, large breasts, standing in garage, vaginal sex with one man, skirt lifted, dim lighting, casual vibe, sharp focus",
            7: "photorealistic 4K, 29-year-old woman, curly red hair, pale skin, small breasts, standing on balcony, vaginal sex with one man, dress lifted, city skyline at dusk, soft glow, high detail",
            8: "high-quality photo, 22-year-old woman, short bob haircut, fair skin, medium breasts, standing in shower, vaginal sex with one man, wet skin, steamy air, soft lighting, realistic detail",
            9: "ultra-sharp 8K, 31-year-old woman, long chestnut hair, tan skin, large breasts, standing in bedroom, vaginal sex with one man, skirt pulled up, warm lamp light, high detail",
            10: "RAW 4K, 27-year-old woman, curly black hair, pale skin, small breasts, standing in elevator, vaginal sex with one man, dress lifted, dim light, urgent pose, realistic textures",
        },
    },
    "mirror selfie": {
        label: "Mirror Selfie",
        prompts: {
            1: "amateur POV, 20-year-old woman, pink hair, petite frame, medium breasts with pierced nipples, nude in bathroom, legs apart, pussy visible in mirror, phone in hand, soft fluorescent lighting, wet tiles, casual vibe, high detail",
            2: "photorealistic 8K, 25-year-old woman, long blonde hair, tan skin, small breasts, nude in bedroom, legs spread, pussy visible in mirror, phone in hand, warm lamp light, realistic textures",
            3: "cinematic 4K, 30-year-old woman, wavy brown hair, pale skin, large breasts, nude in bathroom, legs apart, pussy visible in mirror, phone in hand, steamy air, soft lighting, high detail",
            4: "RAW photo, 22-year-old woman, short black hair, fair skin, medium breasts, nude in closet, legs spread, pussy visible in mirror, phone in hand, dim light, casual vibe, sharp focus",
            5: "hyperrealistic, 28-year-old woman, curly red hair, tan skin, small breasts, nude in bedroom, legs apart, pussy visible in mirror, phone in hand, natural daylight, high detail",
            6: "cinematic NSFW, 33-year-old woman, long dark hair, curvy figure, large breasts, nude in bathroom, legs spread, pussy visible in mirror, phone in hand, soft glow, realistic shadows",
            7: "photorealistic 4K, 26-year-old woman, platinum blonde ponytail, pale skin, medium breasts, nude in hallway, legs apart, pussy visible in mirror, phone in hand, warm lighting, high detail",
            8: "high-quality photo, 29-year-old woman, short bob haircut, tan skin, small breasts, nude in bedroom, legs spread, pussy visible in mirror, phone in hand, soft lamp light, sharp textures",
            9: "ultra-sharp 8K, 31-year-old woman, long chestnut hair, fair skin, large breasts, nude in bathroom, legs apart, pussy visible in mirror, phone in hand, steamy air, high detail",
            10: "RAW 4K, 27-year-old woman, curly black hair, pale skin, medium breasts, nude in dressing room, legs spread, pussy visible in mirror, phone in hand, soft lighting, realistic pores",
        },
    },
    "car backseat": {
        label: "Car Backseat",
        prompts: {
            1: "photorealistic NSFW, 29-year-old woman, dark blonde hair, curvy body, large breasts, sitting in car backseat, legs spread, vaginal creampie from one man, cum dripping, foggy windows, night streetlights, intimate atmosphere, sharp focus",
            2: "cinematic 4K, 25-year-old woman, long black hair, tan skin, medium breasts, lying in car backseat, vaginal sex with one man, legs apart, foggy windows, soft glow, realistic sweat, high detail",
            3: "RAW photo, 30-year-old woman, short blonde hair, pale skin, small breasts, sitting in car backseat, vaginal creampie from one man, cum dripping, night lighting, intimate vibe, sharp focus",
            4: "hyperrealistic, 22-year-old woman, wavy brown hair, fair skin, large breasts, lying in car backseat, vaginal sex with one man, legs spread, foggy windows, streetlights, high detail",
            5: "cinematic NSFW, 33-year-old woman, long dark hair, curvy figure, medium breasts, sitting in car backseat, vaginal creampie from one man, cum dripping, dim interior, soft glow, realistic textures",
            6: "amateur-style 8K, 26-year-old woman, platinum blonde ponytail, tan skin, small breasts, lying in car backseat, vaginal sex with one man, legs apart, foggy windows, night light, high detail",
            7: "photorealistic 4K, 28-year-old woman, curly red hair, pale skin, large breasts, sitting in car backseat, vaginal creampie from one man, cum dripping, soft streetlight glow, sharp focus",
            8: "high-quality photo, 24-year-old woman, short bob haircut, fair skin, medium breasts, lying in car backseat, vaginal sex with one man, legs spread, foggy windows, night setting, realistic detail",
            9: "ultra-sharp 8K, 31-year-old woman, long chestnut hair, tan skin, small breasts, sitting in car backseat, vaginal creampie from one man, cum dripping, dim interior, high detail",
            10: "RAW 4K, 27-year-old woman, curly black hair, pale skin, large breasts, lying in car backseat, vaginal sex with one man, legs apart, foggy windows, soft glow, realistic textures",
        },
    },
    "balcony tease": {
        label: "Balcony Tease",
        prompts: {
            1: "high-quality 8K, 26-year-old woman, long wavy chestnut hair, tan skin, medium breasts, standing nude on balcony, city skyline at dusk, legs slightly apart, pussy visible, gentle breeze, warm sunset glow, cinematic composition",
            2: "photorealistic 4K, 30-year-old woman, long blonde hair, pale skin, small breasts, standing nude on balcony, city lights at night, legs apart, pussy visible, soft glow, realistic textures",
            3: "cinematic 4K, 25-year-old woman, wavy brown hair, tan skin, large breasts, leaning on balcony railing, legs spread, pussy visible, dusk skyline, warm lighting, high detail",
            4: "RAW photo, 22-year-old woman, short black hair, fair skin, medium breasts, standing nude on balcony, city skyline, legs apart, pussy visible, soft breeze, sharp focus",
            5: "hyperrealistic, 28-year-old woman, curly red hair, pale skin, small breasts, sitting on balcony edge, legs spread, pussy visible, night city lights, soft glow, high detail",
            6: "cinematic NSFW, 33-year-old woman, long dark hair, curvy figure, large breasts, standing nude on balcony, city skyline at dusk, legs apart, pussy visible, warm sunset, realistic shadows",
            7: "photorealistic 8K, 26-year-old woman, platinum blonde ponytail, tan skin, medium breasts, leaning on balcony, legs spread, pussy visible, night lights, soft glow, high detail",
            8: "high-quality photo, 29-year-old woman, short bob haircut, fair skin, small breasts, standing nude on balcony, city skyline, legs apart, pussy visible, dusk lighting, sharp textures",
            9: "ultra-sharp 8K, 31-year-old woman, long chestnut hair, tan skin, large breasts, sitting on balcony chair, legs spread, pussy visible, night cityscape, soft glow, high detail",
            10: "RAW 4K, 27-year-old woman, curly black hair, pale skin, medium breasts, standing nude on balcony, city lights, legs apart, pussy visible, warm dusk glow, realistic pores",
        },
    },
};
