// NSFW Presets
const NSFWPresets = {
    none: { label: "Tidak Ada", prompts: {} },
    "cum on face": {
        label: "Cum on Face",
        prompts: generatePrompts("bedroom", [
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude with glossy cum on face from one man, seductive gaze",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude with cum trails on face and body from one man, drooling",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude with cum on face, tongue out, from one man",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude with cum on face and wet skin from one man, intense expression",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude with cum on face and direct eye contact from one man",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude with cum on face and flushed cheeks from one man",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude with cum on face and parted lips from one man",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude with cum on face and sweat on skin from one man",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude with cum on face and dim lighting from one man",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude with cum on face and high detail from one man",
            },
        ]),
    },
    "cumshot on tongue": {
        label: "Cumshot on Tongue",
        prompts: generatePrompts("bedroom", [
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude with thick cum on tongue from one man, tongue out",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude with cum on tongue and wet lips from one man, seductive gaze",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude with cum on tongue and face from one man, drooling",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude with cum on tongue and intense expression from one man",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude with cum on tongue and glistening skin from one man",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude with cum on tongue and high-angle shot from one man",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude with cum on tongue and parted lips from one man",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude with cum on tongue and flushed cheeks from one man",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude with cum on tongue and sweat on skin from one man",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude with cum on tongue and dim lighting from one man",
            },
        ]),
    },
    dildo: {
        label: "Dildo",
        prompts: generatePrompts("bedroom", [
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude using dildo vaginally, legs spread",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude with dildo vaginally, kneeling with intense expression",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude using dildo vaginally, lying down with flushed cheeks",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude with dildo vaginally, dynamic pose with sweat on skin",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude using dildo vaginally, sitting with parted lips",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude with dildo vaginally, legs apart on silk sheets",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude using dildo vaginally, moaning expression",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude with dildo vaginally, seductive gaze",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude using dildo vaginally, high detail",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude with dildo vaginally, dim lighting",
            },
        ]),
    },
    "from behind": {
        label: "From Behind",
        prompts: generatePrompts("bedroom", [
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, lying on stomach, ass and pussy visible from behind",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, all fours, spreading ass, pussy juice visible",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, kneeling, ass up, pussy glistening from behind",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, standing, ass exposed, pussy visible with sweat on skin",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, bending over, ass and pussy in focus",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, on knees, spreading ass, pussy in high detail",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, lying down, ass raised, pussy visible with dim lighting",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, crouching, ass exposed, pussy visible with flushed skin",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, leaning forward, ass and pussy in view, realistic textures",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, on all fours, pussy juice dripping from behind",
            },
        ]),
    },
    "kneeling blowjob": {
        label: "Kneeling Blowjob",
        prompts: generatePrompts("bedroom", [
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, kneeling, performing deepthroat blowjob on one man",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, kneeling, blowjob with saliva dripping on one man",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, kneeling, blowjob with cum on face from one man",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, kneeling, intense blowjob on one man, seductive gaze",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, kneeling, blowjob with drool from one man, flushed cheeks",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, kneeling, blowjob with hand on head from one man",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, kneeling, blowjob with cum dripping from one man",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, kneeling, blowjob with sweat on skin from one man",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, kneeling, blowjob with dim lighting from one man",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, kneeling, blowjob with high detail from one man",
            },
        ]),
    },
    "kneeling tongue out": {
        label: "Kneeling Tongue Out",
        prompts: generatePrompts("bedroom", [
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "wearing decent dress, kneeling with tongue out, (pov), eyes closed, anticipation, (looking up), (close view from top), (facing camera), cinematic, photorealistic",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "wearing decent dress, kneeling with tongue out, (pov), eyes closed, anticipation, (looking up), (close view from top), (facing camera), cinematic, photorealistic",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "wearing decent dress, kneeling with tongue out, (pov), eyes closed, anticipation, (looking up), (close view from top), (facing camera), cinematic, photorealistic",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "wearing decent dress, kneeling with tongue out, (pov), eyes closed, anticipation, (looking up), (close view from top), (facing camera), cinematic, photorealistic",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "wearing decent dress, kneeling with tongue out, (pov), eyes closed, anticipation, (looking up), (close view from top), (facing camera), cinematic, photorealistic",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "wearing decent dress, kneeling with tongue out, (pov), eyes closed, anticipation, (looking up), (close view from top), (facing camera), cinematic, photorealistic",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "wearing decent dress, kneeling with tongue out, (pov), eyes closed, anticipation, (looking up), (close view from top), (facing camera), cinematic, photorealistic",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "wearing decent dress, kneeling with tongue out, (pov), eyes closed, anticipation, (looking up), (close view from top), (facing camera), cinematic, photorealistic",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "wearing decent dress, kneeling with tongue out, (pov), eyes closed, anticipation, (looking up), (close view from top), (facing camera), cinematic, photorealistic",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "wearing decent dress, kneeling with tongue out, (pov), eyes closed, anticipation, (looking up), (close view from top), (facing camera), cinematic, photorealistic",
            },
        ]),
    },
    penetration: {
        label: "Penetration",
        prompts: generatePrompts("bedroom", [
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, missionary position with vaginal penetration by one man, moaning expression",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, cowgirl position with vaginal penetration by one man, sweat on skin",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, doggy-style with vaginal penetration by one man, intense expression",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, reverse cowgirl with vaginal penetration by one man, dynamic angle",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, standing sex with vaginal penetration by one man, flushed cheeks",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, squatting cowgirl with vaginal penetration by one man, realistic textures",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, lying on side with vaginal penetration by one man, dim lighting",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, kneeling with vaginal penetration by one man, seductive gaze",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, sitting with vaginal penetration by one man, parted lips",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, against wall with vaginal penetration by one man, high detail",
            },
        ]),
    },
    "pov blowjob": {
        label: "POV Blowjob",
        prompts: generatePrompts("bedroom", [
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, POV blowjob on one man, deepthroat with saliva dripping",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, POV blowjob with cum on face from one man, intense gaze",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, POV blowjob with wet lips from one man, drooling",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, POV blowjob with cum on tongue from one man, parted lips",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, POV blowjob with hand on head from one man, flushed cheeks",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, POV blowjob with high-angle shot from one man, realistic textures",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, POV blowjob with sweat on skin from one man",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, POV blowjob with dim lighting from one man",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, POV blowjob with seductive gaze from one man",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, POV blowjob with high detail from one man",
            },
        ]),
    },
    "spreading legs": {
        label: "Spreading Legs",
        prompts: generatePrompts("bedroom", [
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, lying on back with legs spread, pussy glistening",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, sitting with legs spread, pussy visible with sweat on skin",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, standing with legs spread, pussy visible with seductive pose",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, kneeling with legs spread, pussy in focus",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, lying with legs spread and masturbating, intense expression",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, sitting with legs spread and wet pussy, flushed cheeks",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, lying with legs spread and cum dripping, dim lighting",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, kneeling with legs spread and realistic textures",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, sitting with legs spread and steamy background",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, standing with legs spread and high detail",
            },
        ]),
    },
    "shower tease": {
        label: "Shower Tease",
        prompts: generatePrompts("shower", [
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, standing in steamy shower with water droplets, seductive pose",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, sitting in shower with legs apart, water streaming",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, leaning against shower wall with wet skin, parted lips",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, standing in shower with soap suds, glistening body",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, sitting in shower with steamy air, intense expression",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, standing in shower with seductive gaze, misty background",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, leaning forward in shower with water dripping, flushed cheeks",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, sitting in shower with warm water, realistic textures",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, standing in shower with misty air, high detail",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, leaning in shower with glistening skin, dim lighting",
            },
        ]),
    },
    "missionary passion": {
        label: "Missionary Passion",
        prompts: generatePrompts("bedroom", [
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, missionary with vaginal penetration by one man, moaning expression",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, missionary with legs spread by one man, sweat on skin",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, missionary with intense expression by one man, flushed cheeks",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, missionary with dynamic angle by one man, realistic textures",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, missionary with wet skin by one man, dim lighting",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, missionary with legs apart on silk sheets by one man",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, missionary with sensual pose by one man, parted lips",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, missionary with realistic textures by one man",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, missionary with high detail by one man",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, missionary with steamy atmosphere by one man",
            },
        ]),
    },
    "topless beach": {
        label: "Topless Beach",
        prompts: generatePrompts("beach", [
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "topless with wet hair and sunglasses, ocean waves in background",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "topless with sandy skin and subtle smile, bright sunlight",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "topless with glistening skin and ocean spray, tan lines visible",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "topless with sandy beach and natural pose, soft breeze",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "topless with waves crashing and warm glow, realistic textures",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "topless with sunny day and detailed pores, ocean horizon",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "topless with wet skin and high detail, gentle waves",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "topless with sandy toes and bright sunlight, natural pose",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "topless with ocean spray and soft glow, realistic textures",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "topless with dusk skyline and warm tones, high detail",
            },
        ]),
    },
    "kitchen seduction": {
        label: "Kitchen Seduction",
        prompts: generatePrompts("kitchen", [
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude with apron, pussy visible, leaning against counter",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude with apron lifted, pussy glistening, seductive pose",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude with apron, legs apart, pussy visible with warm lighting",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude with apron, leaning over, pussy visible with sweat on skin",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude with apron, sitting, pussy in focus, flushed cheeks",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude with apron, standing, pussy visible with realistic textures",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude with apron, legs spread, pussy visible with dim lighting",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude with apron, leaning against counter, pussy visible with high detail",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude with apron, seductive pose, pussy visible with warm tones",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude with apron, wet skin, pussy visible with realistic lighting",
            },
        ]),
    },
    "reverse cowgirl": {
        label: "Reverse Cowgirl",
        prompts: generatePrompts("bedroom", [
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, reverse cowgirl with vaginal penetration by one man, dynamic angle",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, reverse cowgirl with wet skin by one man, intense expression",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, reverse cowgirl with sweating by one man, flushed cheeks",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, reverse cowgirl with legs spread by one man, realistic textures",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, reverse cowgirl with seductive pose by one man, dim lighting",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, reverse cowgirl with realistic textures by one man, parted lips",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, reverse cowgirl with high detail by one man, steamy atmosphere",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, reverse cowgirl with moaning expression by one man",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, reverse cowgirl with sweat on skin by one man",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, reverse cowgirl with dynamic pose by one man",
            },
        ]),
    },
    "bathtub solo": {
        label: "Bathtub Solo",
        prompts: generatePrompts("bathtub", [
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, sitting in bathtub with legs spread, fingering pussy, steamy air",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, lying in bathtub with legs apart, masturbating, candlelight",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, sitting in bubbly bathtub, fingering pussy, glistening skin",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, leaning back in bathtub with legs spread, intense expression",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, sitting in bathtub with wet skin, masturbating, flushed cheeks",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, lying in bathtub with steamy air, fingering pussy, realistic textures",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, sitting in bathtub with warm water, masturbating, dim lighting",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, leaning back in bathtub with bubbly water, fingering pussy, high detail",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, sitting in bathtub with reflective water, masturbating",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, lying in bathtub with warm glow, fingering pussy",
            },
        ]),
    },
    "standing quickie": {
        label: "Standing Quickie",
        prompts: generatePrompts("bedroom", [
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, standing against wall with vaginal penetration by one man, urgent expression",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, standing with skirt lifted, vaginal sex by one man, sweat on skin",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, standing with panties aside, vaginal penetration by one man, flushed cheeks",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, standing in hallway with vaginal sex by one man, dim lighting",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, standing with dress lifted, vaginal sex by one man, realistic textures",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, standing with wet skin, vaginal penetration by one man, intense expression",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, standing with dynamic pose, vaginal sex by one man, parted lips",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, standing with skirt pulled up, vaginal sex by one man, high detail",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, standing with steamy atmosphere, vaginal penetration by one man",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, standing with warm lighting, vaginal sex by one man",
            },
        ]),
    },
    "mirror selfie": {
        label: "Mirror Selfie",
        prompts: generatePrompts("bathroom", [
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, taking mirror selfie with legs apart, pussy visible, steamy background",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, mirror selfie with phone in hand, pussy glistening, wet tiles",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, mirror selfie with seductive pose, pussy visible, misty mirror",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, mirror selfie with wet skin, pussy visible, flushed cheeks",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, mirror selfie with legs spread, pussy in focus, realistic textures",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, mirror selfie with casual vibe, pussy visible, dim lighting",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, mirror selfie with dynamic angle, pussy visible, high detail",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, mirror selfie with warm lighting, pussy visible, seductive pose",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, mirror selfie with misty background, pussy visible, glistening skin",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, mirror selfie with realistic lighting, pussy visible, intense expression",
            },
        ]),
    },
    "car backseat": {
        label: "Car Backseat",
        prompts: generatePrompts("car backseat", [
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, sitting with vaginal creampie from one man, cum dripping, foggy windows, soft glow",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, lying with vaginal sex by one man, foggy windows, dim interior",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, sitting with vaginal creampie, cum dripping, night lights, flushed cheeks",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, lying with vaginal penetration by one man, foggy windows, realistic textures",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, sitting with vaginal sex, foggy windows, soft glow, intense expression",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, lying with vaginal creampie from one man, cum dripping, night setting",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, sitting with vaginal penetration, foggy windows, high detail",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, lying with vaginal sex, foggy windows, warm tones, sweat on skin",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, sitting with vaginal creampie, cum dripping, dim light, parted lips",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, lying with vaginal penetration, foggy windows, realistic textures, steamy atmosphere",
            },
        ]),
    },
    "balcony tease": {
        label: "Balcony Tease",
        prompts: generatePrompts("balcony", [
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, standing with legs apart, pussy visible, city skyline",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, leaning on railing with pussy glistening, dusk lighting",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, sitting with legs spread, pussy visible, night lights",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, standing with gentle breeze, pussy visible, warm glow",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, leaning forward with pussy visible, city lights in background",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, standing with seductive pose, pussy visible, high detail",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, sitting with dusk skyline, pussy glistening, realistic textures",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, leaning on balcony with pussy visible, warm tones",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, standing with night lights, pussy visible, flushed cheeks",
            },
            {
                hairstyle: randomHairStyles(),
                haircolour: randomHairColours(),
                hairAdjective: randomHairAdjective(),
                age: randomAge(),
                attire: "nude, sitting with city skyline, pussy visible, dim lighting",
            },
        ]),
    },
};

// Fungsi untuk memilih warna rambut secara acak
function randomHairColours() {
    return hairColours[Math.floor(Math.random() * hairColours.length)];
}

// Fungsi untuk memilih gaya rambut secara acak
function randomHairStyles() {
    return hairStyles[Math.floor(Math.random() * hairStyles.length)];
}

// Fungsi untuk memilih kata sifat rambut secara acak
function randomHairAdjective() {
    return hairAdjectives[Math.floor(Math.random() * hairAdjectives.length)];
}

// Fungsi untuk menghasilkan usia acak (25-38)
function randomAge() {
    return (Math.random() * 13) | 25;
}

// Fungsi untuk menghasilkan prompt berdasarkan ruangan dan profil
function generatePrompts(room, profiles) {
    return profiles.reduce((prompts, profile, index) => {
        prompts[
            index + 1
        ] = `beautiful ${profile.age}-year-old woman, 1girl, solo, ${profile.hairAdjective} ${profile.hairstyle} ${profile.haircolour} hair, ${profile.attire}, dynamic pose, ${room}, intricate details, realistic skin textures, skin pores`;

        return prompts;
    }, {});
}
